import {describe,it,expect} from 'vitest';
import {createState,execute,forecast,memberAnswer,totals} from '@/lib/connected-demo/core';
import {verify} from '@/lib/connected-demo/verifier';
const corrected=()=>{const s=createState();execute(s,'scan','QA');execute(s,'approve','Automated test · simulated');execute(s,'repair','QA');return s;};
describe('connected synthetic demonstration',()=>{
 it('creates a reproducible source book and exact independent forecast',()=>{const s=createState();expect(s.claims).toHaveLength(100);expect(forecast(s)).toMatchObject({employerReduction:22000,memberReduction:20000,affected:10});expect(totals(s.claims)).toEqual({allowed:572000,member:130000,employer:442000});expect(s.checks).toEqual([]);});
 it('finds actual configuration differences and preserves clean negatives',()=>{const s=createState();execute(s,'scan','QA');expect(s.findings).toHaveLength(2);const clean=createState();clean.config={cashCap:true,copay:2000};execute(clean,'scan','QA');expect(clean.findings).toHaveLength(0);});
 it('blocks unapproved repair and does not alter claims on rejection',()=>{const s=createState(),original=structuredClone(s.claims);expect(()=>execute(s,'repair','QA')).toThrow();execute(s,'scan','QA');execute(s,'reject','QA');expect(()=>execute(s,'repair','QA')).toThrow();expect(s.claims).toEqual(original);expect(s.ledger).toHaveLength(3);});
 it('repairs actual configuration and claims, retaining immutable source and unchanged controls',()=>{const s=corrected();expect(s.original[0].allowed).toBe(12200);expect(s.claims[0]).toMatchObject({allowed:8000,memberPaid:2000,employer:6000,version:2});expect(s.claims.slice(10)).toEqual(s.original.slice(10));expect(s.ledger.filter(e=>e.account==='Claim reversal')).toHaveLength(10);expect(()=>execute(s,'repair','QA')).toThrow();});
 it('does not award a pass before external confirmation',()=>{const s=corrected();expect(verify(s).find(c=>c.name==='Approval and settlement')?.passed).toBe(false);expect(memberAnswer(s,'refund')).toContain('pending');execute(s,'settle','QA');expect(verify(s).every(c=>c.passed)).toBe(true);expect(memberAnswer(s,'refund')).toContain('simulator recorded');});
 it('catches failed corrections, altered invoices, missing reversals and duplicate credits',()=>{for(const mutate of [(s:ReturnType<typeof createState>)=>{s.claims[0].memberPaid=4000;},(s:ReturnType<typeof createState>)=>{s.ledger[0].amount=0;},(s:ReturnType<typeof createState>)=>{s.ledger=s.ledger.filter(e=>e.id!=='SYN-C001-reversal');},(s:ReturnType<typeof createState>)=>{s.ledger.push(s.ledger[0]);},(s:ReturnType<typeof createState>)=>{s.config.cashCap=false;}]){const s=corrected();execute(s,'settle','QA');mutate(s);expect(verify(s).some(c=>!c.passed)).toBe(true);}});
 it('answers from recorded member and settlement data without fabricated payment',()=>{const s=createState();expect(memberAnswer(s,'cost')).toContain('$40.00');expect(memberAnswer(s,'refund')).toContain('No refund');expect(memberAnswer(s,'access')).toContain('not been tested');});
 it('keeps the oracle out of repair code',async()=>{const {readFileSync}=await import('node:fs');expect(readFileSync('src/lib/connected-demo/core.ts','utf8')).not.toMatch(/import.*verifier/);});
});
