import {expect,it} from 'vitest';
import {initial,freeze,hash,SOURCE,type Extraction} from '@/lib/contract-extraction/core';
import {linkRequirement,validateMapping} from '@/lib/assurance/process/guided';
import {newProcess} from '@/lib/assurance/process/source';
import {execute,decide} from '@/lib/assurance/process/processor';
import {playback} from '@/lib/assurance/process/tests';
const mapping={field:'copayCents' as const,value:700,rationale:'A reviewer-defined copay in a synthetic benefit design; not a quoted contract amount.'};
function reviewed(){const s=initial();const raw:Extraction={requirements:[{title:'Benefit design',area:'Formulary',interpretation:'Interpretation for test',implementation:'Proposed configuration',conditions:[],missingDependencies:[],evidence:[{page:59,quote:SOURCE.pages.find(p=>p.page===59)!.text.slice(0,80)}],tests:[{input:'Case',expected:'Result'}]}],limitations:[]};s.original=freeze(raw,s.source);s.originalHash=hash(s.original);s.execution='model';s.status='Complete';s.reviews=[{id:'review-1',requirementId:'term-1',verdict:'Correct',correction:'',note:'',actor:'Test reviewer',at:'2026-09-28T00:00:00Z'}];return s;}
it('freezes actual original, review and mapping separately and passes mapped configuration downstream',()=>{const s=newProcess('wisconsin'),ex=reviewed();linkRequirement(s,ex,'ext_test',3,'term-1',mapping,'QA');expect(s.source.terms.contract[0].values.copayCents).toBe(700);expect(s.contractLink!.requirement.interpretation).toBe('Interpretation for test');ex.original[0].interpretation='Later changed';expect(s.contractLink!.requirement.interpretation).not.toBe('Later changed');execute(s,'contract');expect(s.steps.contract.status).toBe('Awaiting review');expect(s.steps.contract.output?.copayCents).toBe(700);execute(s,'claims');expect(s.steps.claims.status).toBe('Blocked');decide(s,'contract','Approved','QA');playback(s);expect(s.steps.claims.output?.netMemberCents).toBe(700);expect(s.steps.claims.output?.netPlanCents).toBe(410);expect(s.steps.client.output?.netInvoiceCents).toBe(60);});
it('uses corrected human interpretation without rewriting original model output',()=>{const s=newProcess('wisconsin'),ex=reviewed();ex.reviews[0].verdict='Corrected';ex.reviews[0].correction='Corrected meaning';linkRequirement(s,ex,'ext_test',4,'term-1',mapping,'QA');expect(s.contractLink!.review.correction).toBe('Corrected meaning');expect(s.contractLink!.requirement.interpretation).toBe('Interpretation for test');});
it('blocks unreviewed, rejected, tampered and unmatched requirements',()=>{for(const verdict of ['Unsupported','Unverifiable','Duplicate'] as const){const ex=reviewed();ex.reviews[0].verdict=verdict;expect(()=>linkRequirement(newProcess('wisconsin'),ex,'ext_test',0,'term-1',mapping,'QA')).toThrow('Review');}const ex=reviewed();ex.reviews=[];expect(()=>linkRequirement(newProcess('wisconsin'),ex,'ext_test',0,'term-1',mapping,'QA')).toThrow('Review');ex.reviews=reviewed().reviews;ex.original[0].citations[0].matched=false;ex.originalHash=hash(ex.original);expect(()=>linkRequirement(newProcess('wisconsin'),ex,'ext_test',0,'term-1',mapping,'QA')).toThrow('citation');ex.originalHash='changed';expect(()=>linkRequirement(newProcess('wisconsin'),ex,'ext_test',0,'term-1',mapping,'QA')).toThrow('Verified');});
it('rejects unsafe values and requires an explicit mapping rationale',()=>{expect(()=>validateMapping({...mapping,value:-1})).toThrow('value');expect(()=>validateMapping({...mapping,value:true})).toThrow('value');expect(()=>validateMapping({field:'paRequired',value:1,rationale:'test'})).toThrow('value');expect(()=>validateMapping({...mapping,rationale:' '})).toThrow('Explain');});
it('requires separate release approval and preserves rejected results',()=>{const s=newProcess('wisconsin');linkRequirement(s,reviewed(),'ext_test',1,'term-1',mapping,'QA');execute(s,'contract');decide(s,'contract','Rejected','QA');execute(s,'drugs');expect(s.steps.drugs.status).toBe('Blocked');expect(s.steps.contract.status).toBe('Rejected');});
