import {describe,it,expect} from 'vitest';
import {makeFixture,TEMPLATES} from '@/lib/assurance/fixture';
import {detect} from '@/lib/assurance/detector';
import {engineResult} from '@/lib/assurance/engine';
import {prepareAndRepair,review,externalEvidence} from '@/lib/assurance/repair';
import {verify} from '@/lib/assurance/verifier';
import type {State} from '@/lib/assurance/types';
function setup(){const p=makeFixture('tennessee','repeatable',true);const s:State={book:p.book,baseline:structuredClone(p.book),initial:[],findings:[],patches:[],events:[],revision:0,detected:false,score:null};return {p,s};}
describe('production adjudication against independent golden expectations',()=>{
 for(const t of TEMPLATES.filter(t=>t.kind==='engine'))it(t.id,()=>{const {p}=setup();const r=p.book.records.find(r=>r.id===t.id+'-clean')!;expect(engineResult(r,p.book)).toEqual(t.values);});
});
it('all eight areas include bad, clean and unknown records',()=>{const {p}=setup();expect(new Set(p.book.records.map(r=>r.area)).size).toBe(8);for(const t of TEMPLATES)expect(p.book.records.filter(r=>r.control===t.id)).toHaveLength(3);});
it('keeps clean records clear and conflicting or missing terms unknown',()=>{const {p}=setup();const result=detect(p.book);for(const f of result){if(f.recordId.endsWith('-clean'))expect(f.state,f.recordId).toBe('Clear');if(f.recordId.endsWith('-unknown'))expect(f.state,f.recordId).toBe('Not verified');}});
it('repairs only safe records and requires approval for consequential changes',()=>{const {s}=setup();prepareAndRepair(s);expect(s.patches.some(p=>p.state==='Verified')).toBe(true);expect(s.patches.filter(p=>p.review).every(p=>p.state==='Awaiting review')).toBe(true);expect(s.events.some(e=>e.kind==='Applied')).toBe(true);});
it('applies approved roots, discovers downstream repairs and independently verifies them',()=>{const {s,p}=setup();prepareAndRepair(s);for(let pass=0;pass<4;pass++)for(const patch of [...s.patches])if(patch.state==='Awaiting review'){review(s,patch.id,'Approved','Simulated reviewer');if(s.book.records.find(r=>r.id===patch.recordId)?.external)externalEvidence(s,patch.id,'Simulated reviewer');}
 const score=verify(s,p.answer);expect(score.regressions).toBe(0);expect(score.falseAlarms).toBe(0);expect(score.unresolved).toBe(1);expect(score.verifiedRepairs).toBe(TEMPLATES.length-1);expect(s.findings.find(f=>f.control==='notice-deadline'&&f.state==='Exception')?.permanent).toBe(true);
});
it('rejections, repeat decisions and stale repairs cannot create verification',()=>{const {s}=setup();prepareAndRepair(s);const patch=s.patches.find(p=>p.review&&!p.recordId.startsWith('manufacturer'))!;review(s,patch.id,'Rejected','QA');review(s,patch.id,'Rejected','QA');expect(patch.state).toBe('Rejected');expect(()=>review(s,patch.id,'Approved','QA')).toThrow();});
it('does not treat an approved draft as external acceptance',()=>{const {s}=setup();prepareAndRepair(s);const p=s.patches.find(p=>p.recordId==='manufacturer-amount-fault')!;review(s,p.id,'Approved','QA');expect(p.state).toBe('Awaiting review');expect(s.findings.find(f=>f.id===p.recordId)?.state).toBe('Exception');externalEvidence(s,p.id,'QA');expect(p.state).toBe('Verified');});
it('suppresses future records and blocks source incompleteness',()=>{const {p}=setup();p.book.cutoff='2025-12-01';expect(detect(p.book).filter(f=>f.state==='Exception')).toHaveLength(0);p.book.cutoff='2026-05-01';p.book.sourceManifest=null;expect(detect(p.book).every(f=>f.state==='Not verified')).toBe(true);});
it('independent verifier detects tampering and regressions even when a patch is labeled verified',()=>{const {s,p}=setup();prepareAndRepair(s);const r=s.book.records.find(r=>r.id==='network-clean')!;r.actual.network='Wrong';expect(verify(s,p.answer).regressions).toBe(1);});
it('normal collection timing is not an exception; after the deadline a partial receipt is exposure',()=>{const {p}=setup();const r=p.book.records.find(r=>r.id==='partial-collection-fault')!;r.requirements[0].values.dueAt='2026-06-01';expect(detect(p.book).find(f=>f.id===r.id)?.state).toBe('Not due');r.requirements[0].values.dueAt='2026-04-20';expect(detect(p.book).find(f=>f.id===r.id)?.amountCents).toBe(600);});
it('unfavorable guarantee expense persists after the amendment is implemented',()=>{const {s}=setup();prepareAndRepair(s);const p=s.patches.find(p=>p.recordId==='amendment-fault')!;review(s,p.id,'Approved','QA');expect(s.book.records.find(r=>r.id===p.recordId)?.actual.expectedTopupCents).toBe(2000);});
it('blocks stale patch payloads and dependency cycles',()=>{const {s}=setup();prepareAndRepair(s);const p=s.patches.find(p=>p.recordId==='benefits-fault')!;s.book.records.find(r=>r.id===p.recordId)!.actual.copayCents=9900;expect(()=>review(s,p.id,'Approved','QA')).toThrow('Stale');const {p:pack}=setup();pack.book.records[0].dependencies=[pack.book.records[1].id];pack.book.records[1].dependencies=[pack.book.records[0].id];expect(detect(pack.book).find(f=>f.id===pack.book.records[0].id)?.state).toBe('Not verified');});
it('withholds future notice delivery and requires prerequisites',()=>{const {p}=setup();const r=p.book.records.find(r=>r.id==='notice-recipient-clean')!;r.actual.deliveredAt='2026-08-01';expect(detect(p.book).find(f=>f.id===r.id)?.state).toBe('Exception');r.requirements[0].recordedAt='2026-08-01';expect(detect(p.book).find(f=>f.id===r.id)?.state).toBe('Not verified');});
it('is reproducible from a seed and varies corruption across seeds',()=>{const a=makeFixture('wisconsin','a'),b=makeFixture('wisconsin','a'),c=makeFixture('wisconsin','b');expect(a.book).toEqual(b.book);expect(a.book).not.toEqual(c.book);expect(JSON.stringify(a.book)).not.toContain('expectations');});

it('does not disclose fault identities or expected adjudication results in blind inputs',()=>{const {book}=makeFixture('tennessee','private');const text=JSON.stringify(book);expect(text).not.toContain('-fault');expect(text).not.toContain('-clean');expect(text).not.toContain('-unknown');for(const r of book.records.filter(r=>r.kind==='engine'))for(const t of r.requirements)expect(t.values).not.toHaveProperty('status');});
