import { demoFeaturesEnabled } from "@/lib/config";
import Link from "next/link";
import { AgentRefresh } from "@/components/agent-refresh";
import { getClock } from "@/lib/session";
import { AGENTS, AUTONOMY_MEANING, type Autonomy } from "@/lib/agents/registry";
import { nextStep, parseWorkFilters, QUEUES, WORK_STATUSES } from "@/lib/agents/work";
import { getAgentWork, getWorkOverview } from "@/lib/queries/agent-work";
import { getFleet } from "@/lib/queries/agents";
import styles from "./agents.module.css";
export const dynamic = "force-dynamic";
const stamp = (d: Date) => d.toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"UTC"})+" UTC";
export default async function AgentsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const params=await searchParams; const tab=params.tab === "work" || params.tab === "team" ? params.tab : "overview";
  const clock=await getClock(); const overview=await getWorkOverview(clock); const filters=parseWorkFilters(params);
  const work=tab === "work" ? await getAgentWork(clock,filters) : null;
  const fleet=tab === "overview" ? await getFleet(clock) : null;
  const teams=[...new Set(AGENTS.map(a=>a.owner))];
  const workLink=(status:string,agent?:string)=>`/agents?${new URLSearchParams({tab:"work",status,...(agent?{agent}:{})})}`;
  const pageLink=(page:number)=>`/agents?${new URLSearchParams({tab:"work",...filters,page:String(page)})}`;
  return <div className={styles.page}>
    <header className={styles.heading}><div><p className={styles.eyebrow}>PEOPLE & AGENTS</p><h1>Agent operations</h1><p className={styles.muted}>Recorded work, responsible teams and employee handoffs.</p></div><AgentRefresh/></header>
    {demoFeaturesEnabled()&&<p className={styles.note}><Link className={styles.link} href="/rebate-protection">Rebate protection sandbox →</Link> · Simulated reviews and runs are separate from the operational counts below.</p>}
    <nav className={styles.tabs} aria-label="Agent views">{["overview","work","team"].map(t=><Link key={t} href={`/agents?tab=${t}`} aria-current={tab===t?"page":undefined}>{t[0].toUpperCase()+t.slice(1)}</Link>)}</nav>
    <div className={styles.stats}>{[{label:"Awaiting review",count:overview.review,sub:"Proposals for a person"},{label:"Awaiting action",count:overview.action,sub:"Approved, not recorded as applied"},{label:"Failed",count:overview.failed,sub:"Runs that need investigation"}].map(s=><Link key={s.label} href={workLink(s.label)}><span>{s.label === "Failed" ? "Failed runs" : s.label}</span><strong>{s.count.toLocaleString()}</strong><small>{s.sub}</small></Link>)}</div>
    {overview.unavailable>0&&<p className={styles.note}><Link className={styles.link} href={workLink("Status unavailable")}>{overview.unavailable.toLocaleString()} proposals have unavailable status</Link> · History is incomplete at this cutoff; these are excluded from pending counts.</p>}
    {tab === "overview" && <section className={styles.panel}><h2>Agents & responsibilities</h2>{overview.agents.map(a=><article key={a.def.id} className={styles.agent}><div><h3><Link href={`/agents/${a.def.id}`}>{a.def.name}</Link></h3><p>{a.def.purpose}</p>{a.latestSummary&&<p className="mt-3! line-clamp-2"><span className="font-medium">Latest: </span>{a.latestSummary}</p>}</div><div><span className={styles.label}>Responsible team</span><p>{a.def.owner || "Owner not recorded"}</p></div><div><span className={styles.pill} title={AUTONOMY_MEANING[a.autonomy as Autonomy]}>{a.autonomy}</span><p className="mt-2!">{a.latest ? `Last run ${stamp(a.latest)}` : "No recorded activity"}</p></div><div><Link className={styles.link} href={workLink("Unresolved",a.def.id)}>{a.review+a.action} outstanding</Link><p>{a.review} review · {a.action} action</p><Link className={styles.link} href={a.def.id==="leakage-challenge"?"/leakage-challenges":a.def.id==="rebate-protection"?"/rebate-protection":workLink("All",a.def.id)}>{["rebate-protection","leakage-challenge"].includes(a.def.id)?"Sandbox work →":"View work →"}</Link></div></article>)}</section>}
    {work && <section className={styles.panel}><form className={styles.filters} action="/agents"><input type="hidden" name="tab" value="work"/><label>Search<input name="q" defaultValue={filters.q} placeholder="Task or record" maxLength={200}/></label><label>Agent<select aria-label="Agent" name="agent" defaultValue={filters.agent}><option value="">All agents</option>{AGENTS.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Team<select aria-label="Team" name="team" defaultValue={filters.team}><option value="">All teams</option>{teams.map(t=><option key={t}>{t}</option>)}</select></label><label>Status<select aria-label="Status" name="status" defaultValue={filters.status}>{WORK_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><button>Apply</button><Link className={styles.link} href="/agents?tab=work">Reset</Link></form>
      <p className="px-6 py-3 text-[11px] text-ink-500">{work.total.toLocaleString()} records · Runs and proposals are separate. Age is time since recording.</p>
      {work.rows.length ? <div className={styles.scroll}><table className={styles.table}><thead><tr><th>Task</th><th>Agent & team</th><th>Status</th><th>Age</th><th>Next step</th></tr></thead><tbody>{work.rows.map(r=>{const def=AGENTS.find(a=>a.id===r.agentId);return <tr key={`${r.kind}:${r.id}`}><td><Link href={`/agents/runs/${r.runId}${r.kind==="Proposal"?`#proposal-${r.id}`:""}`}>{r.task}</Link><small>{r.kind} · {r.subjectType ?? "Subject not recorded"}</small></td><td>{def?.name??r.agentId}<small>{def?.owner??"Owner not recorded"}</small></td><td><span className={`${styles.pill} ${r.status.startsWith("Awaiting")?styles.warm:r.status==="Failed"?styles.bad:""}`}>{r.status}</span>{r.kind==="Proposal"&&<small>Run: {r.outcome}</small>}</td><td className="whitespace-nowrap">{Math.floor((clock.now.getTime()-r.at.getTime())/86400000)}d<small>{stamp(r.at)}</small></td><td>{nextStep(r.status)}</td></tr>})}</tbody></table></div>:<p className={styles.empty}>No work matches these filters.</p>}
      <nav className={styles.pages} aria-label="Work pages"><span>Page {work.page} of {work.pages}</span><div className="flex gap-5">{work.page>1&&<Link href={pageLink(work.page-1)}>Previous</Link>}{work.page<work.pages&&<Link href={pageLink(work.page+1)}>Next</Link>}</div></nav>
    </section>}
    {tab === "team" && <><p className={styles.note}>Responsible roles, not assigned employees. Names appear only when a review is recorded.</p><div className={styles.teams}>{teams.map(team=><section key={team} className={`${styles.panel} ${styles.team}`}><span className={styles.label}>Responsible team</span><h2>{team}</h2>{overview.agents.filter(a=>a.def.owner===team).map(a=><div key={a.def.id}><h3>{a.def.name}</h3><p>{a.def.purpose}</p><span className={styles.label}>Employee handoff</span><p>{QUEUES[a.def.id]?.handoff??"Handoff not documented."}</p><div className="flex flex-wrap gap-5"><Link className={styles.link} href={workLink("Unresolved",a.def.id)}>{a.review+a.action} outstanding</Link><Link className={styles.link} href={QUEUES[a.def.id]?.href??"/agents"}>{QUEUES[a.def.id]?.label??"Work queue"} →</Link></div></div>)}</section>)}</div></>}
    {fleet&&<details className={`${styles.panel} ${styles.details}`}><summary>Execution & estimates</summary><p className="mt-4">{fleet.totalRuns.toLocaleString()} recorded runs · {fleet.modelRuns.toLocaleString()} model-driven. Each run distinguishes model and scripted execution.</p><p className="mt-2">Model spend ${(fleet.totalCostMillicents/100000).toFixed(2)} · Estimated staff time equivalent {Math.round(fleet.hoursDisplaced).toLocaleString()} hours. Based on per-task assumptions, not measured savings.</p><p className="mt-2">{fleet.totalHeld.toLocaleString()} historical consequential proposals. This is not the outstanding review count.</p></details>}
    <footer className={styles.note}>Data cutoff {stamp(clock.now)} · Updated {stamp(new Date())}. Refreshed on load or request; no live execution tracking.</footer>
  </div>;
}
