"use client";
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export function AssuranceActions({id,revision=0,patchId,external=false,reviewed=false,externalKind}:{id?:string;revision?:number;patchId?:string;external?:boolean;reviewed?:boolean;externalKind?:string}){
 const router=useRouter(),key=useRef<string|null>(null);const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(action:string,decision?:string){setBusy(true);setError('');try{key.current??=crypto.randomUUID();const body=action==='create'?{action,key:key.current}:{action,id,revision,...(patchId?{patchId}:{}),...(decision?{decision}:{})};const r=await fetch('/api/operational-assurance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);if(action==='create'){key.current=null;router.push(`/rebate-protection?run=${data.id}`);}router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to complete action');}finally{setBusy(false);}}
 const cls='rounded-lg border border-ink-200 bg-white px-4 py-2 text-xs text-ink-800 disabled:opacity-50';
 return <div className="flex flex-wrap items-center gap-3">{!id?<button disabled={busy} className={cls} onClick={()=>send('create')}>Create blind test book</button>:!patchId?<button disabled={busy} className={cls} onClick={()=>send('run')}>Run checks &amp; safe fixes</button>:reviewed&&external?<button disabled={busy} className={cls} onClick={()=>send('external')}>Record simulated {externalKind==='notice'?'delivery':externalKind==='collection'?'settlement':'acceptance'}</button>:<><button disabled={busy} className={cls} onClick={()=>send('review','Approved')}>Approve sandbox correction</button><button disabled={busy} className={cls} onClick={()=>send('review','Rejected')}>Reject</button></>}{busy&&<span role="status" className="text-xs">Saving and retesting…</span>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
