import Link from 'next/link';
import {notFound} from 'next/navigation';
import {selectedSponsor} from '@/lib/contract-checks/context';
import {getClock} from '@/lib/session';
import {readAssurance,recentAssurance} from '@/lib/assurance/service';
import {AREAS,type Values} from '@/lib/assurance/types';
import {ContractLanguage} from './assurance-contract-language';
import {AssuranceActions} from './assurance-actions';
import styles from './rebate-protection.module.css';
function RecordValues({values}:{values:Values|null}){
 if(!values)return <p>Not verified</p>;
 return <dl className="space-y-2 rounded-lg bg-ink-50 p-4 text-sm">{Object.entries(values).map(([key,value])=><div key={key} className="flex flex-wrap justify-between gap-3"><dt className="text-ink-500">{key.replace(/Cents$|Bps$/,'').replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</dt><dd className="font-medium">{typeof value==='number'&&key.endsWith('Cents')?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100):typeof value==='number'&&key.endsWith('Bps')?`${(value/100).toFixed(2)}%`:typeof value==='boolean'?value?'Yes':'No':value===null?'Not recorded':String(value)}</dd></div>)}</dl>;
}
export async function AssuranceWorkspace({id,area,tab}:{id?:string;area?:string;tab?:string}){
 const sponsor=await selectedSponsor(),clock=(await getClock()).now,recent=await recentAssurance(sponsor,clock);
 const run=id?await readAssurance(id,sponsor,clock):null;if(id&&!run)notFound();
 const state=run?.state,findings=state?.findings??[],score=state?.score;
 const selected=area!==undefined&&/^\d$/.test(area)&&Number(area)<8?Number(area):null;
 return <div className={styles.page}>
 <header className={styles.header}><div><span className={styles.eyebrow}>{sponsor} · Operational leakage protection</span><h1>Leakage controls</h1><p className={styles.muted}>Detect the issue. Correct the record. Verify the result.</p></div><span className={styles.badge}>Scripted execution · Synthetic book</span></header>
 <div className="flex flex-wrap gap-5"><Link href="/contract-checks">Rebate transaction checks →</Link><Link href="/leakage-challenges">Earlier blind challenges →</Link>{sponsor==='wisconsin'&&<Link href="/rebate-protection?tab=scenarios">Earlier rebate scenarios →</Link>}<Link href="/agents/rebate-protection">Agent responsibilities →</Link></div>
 <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Eight areas. One evidence trail.</h2><p>Contract and event terms are synthetic assumptions, not actual {sponsor==='tennessee'?'Tennessee':'Wisconsin'} provisions. The answer key stays hidden until checks and safe repairs finish.</p></div><AssuranceActions/></div><p className={styles.note}>No real claims, benefits, rates, notices or payments change. Recorded execution only; refresh to load saved results.</p></section>
 {recent.length>0&&<nav className={styles.recent} aria-label="Recent assurance runs">{recent.map(r=><Link key={r.id} href={`/rebate-protection?run=${r.id}`}>{r.createdAt.toISOString().slice(0,19).replace('T',' ')} UTC</Link>)}</nav>}
 {!run?<section className={styles.panel}><h2>Control coverage</h2><div className="grid gap-4 sm:grid-cols-2">{AREAS.map((a,i)=><div key={a} className="rounded-lg border border-ink-100 p-4"><h3>{i+1}. {a}</h3><p>Create a book to inspect clean records, undisclosed errors and missing evidence.</p></div>)}</div></section>:<>
 <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>{state!.detected?'Checks recorded':'Ready to check'}</h2><p>{state!.book.records.length} supplied records · Cutoff {state!.book.cutoff.slice(0,10)} · Revision {run.revision}</p></div><AssuranceActions id={run.id} revision={run.revision}/></div><div className="mt-4 flex flex-wrap gap-5"><Link href={`/api/operational-assurance?id=${run.id}`}>Export evidence →</Link><Link href={`/agents/runs/${run.id}`}>Agent work →</Link><Link href={`/rebate-protection?run=${run.id}`}>Refresh</Link></div></section>
 <nav className={styles.tabs} aria-label="Assurance views">{[['controls','Controls'],['proof','Proof'],['history','History']].map(([t,label])=><Link key={t} href={`/rebate-protection?run=${run.id}&tab=${t}`} aria-current={(tab??'controls')===t?'page':undefined}>{label}</Link>)}</nav>
 {tab==='proof'?<section className={styles.panel}><h2>Detection and resolution proof</h2>{!score?<p>Run checks to freeze findings and reveal the independent answer.</p>:<><div className={styles.metrics}>{[['Detected initially',score.detected],['Missed / blocked initially',score.missed],['Verified repairs',score.verifiedRepairs],['Remaining faulty records',score.unresolved],['False alarms',score.falseAlarms],['Exact amounts',score.exactAmounts],['Regressions',score.regressions],['Not verified',score.unverified]].map(([label,n])=><article key={label}><span>{label}</span><strong>{n}</strong></article>)}</div><p className={styles.note}>The verifier compares working records with a separately authored answer. Blocked downstream records count as initially missed until their dependencies are resolved. Unknown evidence is not a pass. Same-application separation is not an independent external audit.</p><p>No realized recovery is claimed. Corrections, collection exposure, valid employer entitlements and settled cash are different measures. Amounts from overlapping controls are not added as savings.</p><details><summary>Record-level proof · {score.details.length} expectations</summary>{score.details.map(d=><p key={d.id}>{d.id}: {d.detection} · {d.resolution}</p>)}</details></>}
 <details><summary>Frozen inputs, commitment and execution versions</summary><pre>{JSON.stringify({versions:run.versions,inputHash:run.inputHash,answerCommitment:run.commitment,answer:run.answer},null,2)}</pre></details></section>:tab==='history'?<section className={styles.panel}><h2>Correction history</h2><p>Wall-clock recording time is separate from this synthetic book’s evidence cutoff. All decisions and external responses below are simulated.</p>{state!.events.length?<ol className={styles.timeline}>{state!.events.map(e=><li key={e.id}><span>{e.at} · {e.actor}</span><h3>{e.kind}</h3><p>{e.recordId} · {e.detail}</p>{e.before&&<details><summary>Record change</summary><pre>{JSON.stringify({before:e.before,after:e.after},null,2)}</pre></details>}</li>)}</ol>:<p>No actions recorded.</p>}</section>:<>
 <section className={styles.panel}><h2>Coverage by area</h2><div className="grid gap-4 sm:grid-cols-2">{AREAS.map((a,i)=>{const f=findings.filter(f=>f.area===i),verified=state!.patches.filter(p=>p.state==='Verified'&&state!.book.records.find(r=>r.id===p.recordId)?.area===i).length;return <Link key={a} className="rounded-lg border border-ink-100 p-4" href={`/rebate-protection?run=${run.id}&area=${i}`}><h3>{i+1}. {a}</h3><p>{f.filter(f=>f.state==='Clear'||f.state==='Exception').length} evaluated · {f.filter(f=>f.state==='Exception').length} exceptions · {f.filter(f=>f.state==='Not verified').length} unknown · {verified} verified repairs</p><p>Open exposure: {f.filter(f=>f.state==='Exception'&&f.amountCents!==null).length} quantified records · {f.filter(f=>f.state==='Exception'&&f.amountCents===null).length} unquantified. Open records for amounts; controls may overlap.</p></Link>;})}</div></section>
 <section className={styles.panel}><div className={styles.sectionHeading}><h2>{selected===null?'Controls and exceptions':AREAS[selected]}</h2>{selected!==null&&<Link href={`/rebate-protection?run=${run.id}`}>All areas</Link>}</div>{!state!.detected?<p>No results yet. Run checks &amp; safe fixes.</p>:findings.filter(f=>selected===null||f.area===selected).sort((a,b)=>Number(a.state==='Clear')-Number(b.state==='Clear')).map(f=>{const r=state!.book.records.find(r=>r.id===f.recordId),p=state!.patches.find(p=>p.recordId===f.recordId),reviewed=state!.events.some(e=>e.recordId===f.recordId&&e.kind==='Simulated review'&&e.detail==='Approved');return <details key={f.id}><summary><strong>{f.label}</strong> · {f.state}{p?` · ${p.state}`:''}</summary><div className="my-4 space-y-3"><p>{f.reason}</p><p>{r?.owner??'Data operations'} · Responsible role, not employee assignment</p><p className="break-all">{f.recordId} · {r?.claimId} · {r?.memberId} {r?.invoiceId?`· ${r.invoiceId}`:''}</p><p>Financial stakeholders: {f.area===2?'Member, employer and pharmacy':f.area===5?'Employer and PBM':f.area===6?'Manufacturer, employer and PBM':'Employer and PBM'}. No reduction in contractual entitlements is credited as savings.</p><p>Record discrepancy: {f.state==='Clear'?'No remaining discrepancy':f.amountCents===null?'Not quantified':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(f.amountCents/100)}. Not additive savings.</p><div className="grid items-start gap-5 xl:grid-cols-3"><ContractLanguage record={r} cutoff={state!.book.cutoff}/><div className="min-w-0"><h3>Expected</h3><RecordValues values={f.expected}/></div><div><h3>Recorded</h3><RecordValues values={f.actual}/></div></div>{p?.state==='Awaiting review'&&<AssuranceActions id={run.id} revision={run.revision} patchId={p.id} external={r?.external} externalKind={r?.kind} reviewed={reviewed}/>}<details><summary>Terms, dependencies and verification</summary><pre>{JSON.stringify({requirements:r?.requirements,basis:r?.basis,dependencies:r?.dependencies,patch:p,independent:score?.details.find(d=>d.id===f.recordId)},null,2)}</pre></details></div></details>;})}</section></>}
 </>}
 <p className={styles.note}>Results demonstrate only these defined controls and records. Missing evidence and an expired notice deadline remain visible. A clean test suite does not establish zero operational leakage.</p>
 </div>;
}
