'use client';
import {useEffect,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import type {State,TERMS,forecast} from '@/lib/connected-demo/core';
import css from './connected-demo.module.css';
const cash=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n/100);
type Data={run:{id:string;revision:number;state:State}|null;terms:typeof TERMS;forecast:ReturnType<typeof forecast>;answers:{cost:string;refund:string;access:string}};
const tabs=[['overview','Overview'],['design','Benefit design'],['claims','Claims'],['work','Work'],['money','Money'],['service','Member service'],['proof','Proof']];
const next:Record<State['stage'],{action:string;label:string;hint:string}>={Ready:{action:'scan',label:'Run checks',hint:'Compare implementation with the amendment.'},Detected:{action:'approve',label:'Approve sandbox correction',hint:'Simulated Benefits / Finance review. Changes member cost and payment amounts.'},Approved:{action:'repair',label:'Apply correction',hint:'Reprocess the ten affected claims and adjust the invoice.'},Rejected:{action:'scan',label:'Review again',hint:'The rejected correction has not changed any claim.'},Corrected:{action:'settle',label:'Simulate settlement',hint:'Record fictional pharmacy recovery and member refund confirmations.'},Settled:{action:'verify',label:'Verify results',hint:'Check exact amounts, unchanged members and every dollar.'},Verified:{action:'verify',label:'Run verification again',hint:'All defined checks passed. Broader operational performance remains unproven.'}};
export function ConnectedDemo({canRun}:{canRun:boolean}){
 const q=useSearchParams(),router=useRouter(),params=q.toString(),tab=q.get('view')??'overview';
 const [loaded,setLoaded]=useState<{params:string;data:Data}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[claim,setClaim]=useState(0),[question,setQuestion]=useState<'cost'|'refund'|'access'>('cost');
 useEffect(()=>{const controller=new AbortController();fetch('/api/operating-demo?'+params,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setLoaded({params,data:d});setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[params,refresh]);
 const data=loaded?.params===params?loaded.data:null;
 const nav=(view:string)=>{const p=new URLSearchParams(params);p.set('view',view);router.replace('/operating-demo?'+p,{scroll:false});};
 async function act(action:string){setBusy(true);setError('');try{const body={action,key:crypto.randomUUID(),...(action!=='create'&&data?.run?{id:data.run.id,revision:data.run.revision}:{})};const r=await fetch('/api/operating-demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);const p=new URLSearchParams(params);p.set('id',d.id);router.replace('/operating-demo?'+p,{scroll:false});setRefresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const s=data?.run?.state,f=data?.forecast,step=s?next[s.stage]:null,corrected=s&&['Corrected','Settled','Verified'].includes(s.stage),settled=s&&['Settled','Verified'].includes(s.stage),selected=s?.claims[claim];
 return <div className={css.page}>
  <header className={css.header}><div><p className={css.eyebrow}>Cedar Works · 100 fictional members</p><h1>A promise, kept.</h1><p>Follow one benefit change from the contract to the member.</p></div><div className={css.headerLinks}><a href="/public-data-checks">Public sources ↗</a><a href="/versions">Versions ↗</a></div></header>
  <div className={css.notice}><span>Synthetic demonstration</span> All members, terms, claims and financial results in this workspace are fictional. Scripted agents use deterministic processing; no real benefits or payments change. Sponsor selection scopes saved runs only.</div>
  <nav className={css.nav} aria-label="Connected workspace">{tabs.map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>nav(id)}>{label}</button>)}</nav>
  {error&&<p className={css.error} role="alert">{error}</p>}
  {!data&&!error&&<p role="status">Loading demonstration…</p>}
  {data&&<>
   <section className={css.hero}><div><span className={css.heroLabel}>{s?.stage??'Ready to explore'}</span><h2>{s?.stage==='Verified'?'The correction holds.':corrected?'Corrected. Follow the money.':s?.stage==='Detected'?'Two terms. Ten affected members.':'Lower cost. No new access restrictions.'}</h2><p>{step?.hint??'A stale copay and missing cash-price cap flow into claims, the employer invoice and a member’s bill. Follow the correction across every team.'}</p><p className={css.recorded}>{s?`Last recorded action · ${new Date(s.events.at(-1)!.at).toLocaleString()}`:'Recorded execution · No background monitoring'}</p></div><div className={css.actions}><button className={css.primary} disabled={busy||!canRun} onClick={()=>act(step?.action??'create')}>{busy?'Working…':step?.label??'Start demonstration'}</button>{s?.stage==='Detected'&&<button disabled={busy||!canRun} onClick={()=>act('reject')}>Reject correction</button>}{s&&<button disabled={busy||!canRun} onClick={()=>act('create')}>Start fresh run</button>}{!canRun&&<small>Return to the current clock to run.</small>}</div></section>
   <section className={css.metrics}><div><span>Employer cost reduction</span><strong>{cash(f!.employerReduction)}</strong><small>{settled?'Simulated settlement confirmed':'Forecast for this 100-claim book'}</small></div><div><span>Member cost reduction</span><strong>{cash(f!.memberReduction)}</strong><small>{settled?'Simulated refunds confirmed':'10 members · $20 each'}</small></div><div><span>Unchanged members</span><strong>90 <i>/ 100</i></strong><small>No new access restrictions modeled</small></div><div><span>Verified checks</span><strong>{s?.checks.filter(c=>c.passed).length??0} <i>/ 7</i></strong><small>{s?.stage==='Verified'?'Defined synthetic cases only':'Run the full cycle to verify'}</small></div></section>
   {tab==='overview'&&<><div className={css.sectionTitle}><h2>One change. Every handoff.</h2><span>Explore any area</span></div><div className={css.cards}>{[
    ['design','01','Account management','Evaluate the change','$220 lower employer cost, with $200 returned to members.'],['claims','02','Claims operations','Explain the prescription','Trace the rule, price, member share and employer cost.'],['work','03','Benefits / Finance','Close the exception','Find the mismatch, approve the patch and verify the correction.'],['money','04','Finance','Follow every dollar','Preserve the original invoice and show each adjustment.'],['service','05','Member service','Resolve the question','Explain the claim and show whether the refund is pending or settled.'],['proof','06','Independent verification','Inspect the result','Check exact amounts, control claims and balanced financial effects.']
   ].map(([view,n,role,title,desc])=><button className={css.card} key={view} onClick={()=>nav(view)}><span>{n} <small>{role}</small></span><h3>{title}</h3><p>{desc}</p><b aria-hidden="true">↗</b></button>)}</div></>}
   {tab==='design'&&<div className={css.two}><section className={css.panel}><p className={css.eyebrow}>Proposed configuration</p><h2>Protect the member. Reduce the bill.</h2><p>Restore the cash-price cap and implement the $20 copay for the ten designated claims. No drugs or pharmacies are removed.</p><dl><div><dt>Employer claim cost</dt><dd>{cash(f!.before.employer)} → {cash(f!.after.employer)}</dd></div><div><dt>Member cost</dt><dd>{cash(f!.before.member)} → {cash(f!.after.member)}</dd></div><div><dt>Members affected</dt><dd>{f!.affected} of 100</dd></div><div><dt>Rebates and fees</dt><dd>$50 credited · $200 disclosed</dd></div></dl><p className={css.note}>Forecast calculated on the same 100 claims. No annual extrapolation or medical-cost savings.</p></section><section className={css.panel}><p className={css.eyebrow}>Exact requirement</p><h2>{data.terms.id}</h2><blockquote>{data.terms.quote}</blockquote><p>{data.terms.label} · Effective {data.terms.effective}</p><p className={css.note}>Source → cash-price cap included; target copay $20; all rebates credited. The source is synthetic and is not attributed to a public contract.</p></section></div>}
   {tab==='claims'&&<section className={css.panel}><div className={css.sectionTitle}><h2>Prescription trace</h2><label>Claim <select value={claim} onChange={e=>setClaim(Number(e.target.value))}>{Array.from({length:100},(_,i)=><option value={i} key={i}>SYN-C{String(i+1).padStart(3,'0')} · {i<10?'Affected':'Control'}</option>)}</select></label></div>{selected?<><p>{selected.member} · Fictional maintenance medicine · {selected.target?'Amendment population':'Outside amendment population'}</p><div className={css.trace}><div><span>Submitted + fee</span><strong>{selected.target?'$120 + $2':'$48 + $2'}</strong></div><div><span>Cash-price cap</span><strong>{selected.target?'$80':'$50'}</strong></div><div><span>Recorded allowed</span><strong>{cash(selected.allowed)}</strong></div><div><span>Member / employer</span><strong>{cash(selected.memberPaid)} / {cash(selected.employer)}</strong></div></div><p>{selected.target?(selected.version===1?'The original configuration omits the cash-price cap and uses the old $40 copay.':'Version 2 applies the cap and $20 copay. Original results remain in the export.'):'This control claim should not change.'}</p><details><summary>Original → produced → expected</summary><pre>{JSON.stringify({original:s!.original[claim],produced:selected,expected:selected.target?{allowed:8000,memberPaid:2000,employer:6000}:{allowed:5000,memberPaid:1000,employer:4000},units:'cents'},null,2)}</pre></details><p className={css.note}>Uses Glass’s existing lesser-of pricing function. Coverage, clinical safety and accumulator processing are outside this demonstration.</p></>:<p>Start a run to generate the book.</p>}</section>}
   {tab==='work'&&<div className={css.two}><section className={css.panel}><h2>Correction queue</h2>{s?.findings.length?s.findings.map(c=><div className={css.finding} key={c.field}><h3>{c.field}</h3><p>Expected: {c.expected} · Detected: {c.actual}</p><p>Current: {corrected?c.expected:c.actual} · {corrected?'Applied; inspect verification':'Awaiting correction'}</p></div>):<p>Run checks to compare the implementation with the amendment.</p>}<p>Responsible roles: Benefits and Finance. These are roles, not employee assignments.</p>{s?.reviewer&&<p>Simulated reviewer: {s.reviewer}</p>}</section><section className={css.panel}><h2>Recorded handoffs</h2><ol className={css.timeline}>{s?.events.map((e,i)=><li key={i}><strong>{e.role}</strong><p>{e.action}</p><small>{new Date(e.at).toLocaleString()}</small></li>)}</ol></section></div>}
   {tab==='money'&&<section className={css.panel}><div className={css.sectionTitle}><h2>Claim to cash</h2><span>{settled?'Synthetic confirmations recorded':'Settlement is not yet complete'}</span></div><div className={css.trace}><div><span>Original invoice</span><strong>$4,570</strong></div><div><span>Adjustment</span><strong>{corrected?'−$220':'Not posted'}</strong></div><div><span>Current invoice</span><strong>{corrected?'$4,350':'$4,570'}</strong></div><div><span>Member refunds</span><strong>{corrected?'$200':'Not posted'}</strong></div></div><p>The $420 pharmacy recovery funds $220 of employer credit and $200 of member refunds. These are parts of one correction, not three savings totals. The employer keeps its $50 rebate credit.</p>{s?.ledger.filter(e=>!e.account.startsWith('Claim ')).map(e=><div className={css.ledger} key={e.id}><div><strong>{e.account}</strong><p>{e.reason}</p></div><strong>{cash(e.amount)}</strong><span>{e.status}</span></div>)}<details><summary>Claim reversals and replacements</summary>{s?.ledger.filter(e=>e.account.startsWith('Claim ')).map(e=><p key={e.id}>{e.id} · {cash(e.amount)} · {e.reason}</p>)}</details></section>}
   {tab==='service'&&<div className={css.two}><section className={css.panel}><p className={css.eyebrow}>Demo member 001 · SYN-C001</p><h2>A clear answer, tied to the claim.</h2><p>Choose a member question. The response reads the current claim and settlement state.</p><div className={css.questions}>{[['cost','Why did my prescription cost more?'],['refund','Has my refund been paid?'],['access','Will my access change?']].map(([key,label])=><button key={key} aria-pressed={question===key} onClick={()=>setQuestion(key as typeof question)}>{label}</button>)}</div></section><section className={css.answer}><span>Member service · Scripted response</span><h2>{question==='refund'?'Refund status':question==='access'?'Access':'Your prescription'}</h2><p>{data.answers[question]}</p><button onClick={()=>{setClaim(0);nav('claims');}}>Open supporting claim →</button><p className={css.note}>No live call, generated medical advice or invented employee conversation.</p></section></div>}
   {tab==='proof'&&<section className={css.panel}><div className={css.sectionTitle}><div><p className={css.eyebrow}>Independent expected outcomes · Version 1</p><h2>{s?.stage==='Verified'?'No unresolved discrepancies in the tested records.':'Evidence before conclusions.'}</h2></div>{data.run&&<a href={`/api/operating-demo?id=${data.run.id}&export=1`}>Export evidence ↗</a>}</div><p>100 synthetic claims. Ten affected members. Ninety unchanged controls. Recorded approval, claim corrections, invoice adjustment and simulated settlement must all agree.</p>{s?.checks.length?s.checks.map(c=><div className={css.check} key={c.name}><span>{c.passed?'Passed':'Failed'}</span><div><strong>{c.name}</strong><p>{c.detail}</p></div></div>):<p className={css.notice}>Not tested yet. Complete correction and simulated settlement, then run verification.</p>}<p className={css.note}>This proves defined synthetic outcomes, not zero leakage across every contract or future event. No actual Caremark savings or member outcomes are claimed.</p><details><summary>Execution and history</summary><p>{s?.engine} · All financial calculations deterministic. This workspace does not write operational claims, agent queues or payment records.</p><a href="https://github.com/atrix25/glass-pbm/tree/glass-public-data-baseline-cd9d126">Browse the preserved source version ↗</a></details></section>}
  </>}
 </div>;
}
