'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export function ContractMappingForm({extractionId,extractionRevision,requirementId}:{extractionId:string;extractionRevision:number;requirementId:string}){
 const router=useRouter(),[field,setField]=useState('paRequired'),[value,setValue]=useState('false'),[rationale,setRationale]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<{body:string;key:string}|null>(null);
 const boolean=['paRequired','stepRequired'].includes(field);
 async function create(){setBusy(true);setError('');const payload={action:'create',scenario:'clean',link:{extractionId,extractionRevision,requirementId,mapping:{field,value:boolean?value==='true':Number(value),rationale}}},body=JSON.stringify(payload);if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()};try{const r=await fetch('/api/operational-assurance/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,key:pending.current.key})});const data=await r.json();if(!r.ok)throw Error(data.error);router.push(`/rebate-protection?run=${data.id}&area=contract&tab=process`);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to create flow');}finally{setBusy(false);}}
 const cls='mt-2 w-full rounded-lg border border-ink-200 bg-white p-3 text-sm';
 return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Configuration field<select className={cls} value={field} onChange={e=>{setField(e.target.value);setValue(['paRequired','stepRequired'].includes(e.target.value)?'false':'');}}><option value="paRequired">Prior authorization required</option><option value="stepRequired">Step therapy required</option><option value="copayCents">Member copay (cents)</option><option value="quantityLimit">Quantity limit (per 30 days)</option></select></label><label className="text-sm">Expected sandbox value{boolean?<select className={cls} value={value} onChange={e=>setValue(e.target.value)}><option value="false">No</option><option value="true">Yes</option></select>:<input className={cls} type="number" min={field==='quantityLimit'?1:0} max={100000} step={1} value={value} onChange={e=>setValue(e.target.value)}/>}</label></div><label className="block text-sm">Mapping rationale<textarea className={cls} rows={3} value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Explain how this setting exercises the clause and which details remain assumptions."/></label><p className="text-xs text-ink-500">This is a reviewer-defined test setting. It is not automatically extracted from the contract. Other fields, claims and business dates remain synthetic. This first connection supports copay, quantity limit, PA and step therapy; other clauses remain review-only.</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I reviewed this mapping and its demo assumptions.</label><button className="rounded-lg bg-ink-800 px-5 py-3 text-sm text-white disabled:opacity-40" disabled={busy||!ack||!rationale.trim()||!value} onClick={create}>{busy?'Creating…':'Create implementation flow →'}</button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
