import Link from 'next/link';
import {notFound} from 'next/navigation';
import {selectedSponsor} from '@/lib/contract-checks/context';
import {SOURCE,metrics,normalize,AREAS} from '@/lib/contract-extraction/core';
import {available} from '@/lib/contract-extraction/extract';
import {readExtraction,recentExtractions} from '@/lib/contract-extraction/service';
import {ExtractionActions} from './contract-extraction-actions';
import styles from './rebate-protection.module.css';
import css from './process-workspace.module.css';
export async function ContractExtractionWorkspace({id:requestedId,tab='requirements',term,area}:{id?:string;tab?:string;term?:string;area?:string}){
 const sponsor=await selectedSponsor(),recent=await recentExtractions(sponsor),id=requestedId??recent[0]?.id,run=id?await readExtraction(id,sponsor):null;if(id&&!run)notFound();
 const state=run?.state,source=state?.source??SOURCE,m=state?metrics(state):null,filtered=state?.original.filter(r=>!area||r.area===area)??[],selected=filtered.find(r=>r.id===term)??filtered.find(r=>r.area==='Guarantee eligibility')??filtered[0],review=state?.reviews.findLast(r=>r.requirementId===selected?.id);
 const url=(view=tab,selectedId=selected?.id,filter=area)=>'/contract-extraction?'+new URLSearchParams({...(id?{run:id}:{}),tab:view,...(selectedId?{term:selectedId}:{}),...(filter?{area:filter}:{})});
 return <div className={styles.page}>
 <header className={styles.header}><div><span className={styles.eyebrow}>Public contract · Human verification</span><h1>Contract extraction</h1><p className={styles.muted}>The source. The AI’s interpretation. Your verdict.</p></div><Link href="/rebate-protection">Processing flows →</Link></header>
 <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>{source.title}</h2><p>{source.pages.length} selected pages of {source.totalPages} · Historical reference, not current {sponsor==='tennessee'?'Tennessee':'client'} configuration</p></div><ExtractionActions configured={available()} running={state?.status==='Running'||state?.status==='Queued'}/></div><p className={styles.note}>{source.scope}</p><div className={css.linked}><a href={source.localUrl} target="_blank" rel="noreferrer">Original PDF ↗</a><a href={source.url} target="_blank" rel="noreferrer">Publisher ↗</a>{id&&<><Link href={url()}>Refresh</Link><Link href={`/api/contract-extraction?id=${id}`}>Export evidence</Link></>}</div></section>
 {recent.length>0&&<nav aria-label="Extraction runs" className={styles.recent}>{recent.map(r=><Link key={r.id} href={`/contract-extraction?run=${r.id}`}>{r.createdAt.toISOString().slice(0,19).replace('T',' ')} UTC</Link>)}</nav>}
 <nav className={styles.tabs} aria-label="Contract extraction views">{[['requirements','Requirements'],['pages','Source pages'],['accuracy','Accuracy']].map(([t,label])=><Link key={t} href={url(t)} aria-current={tab===t?'page':undefined}>{label}</Link>)}</nav>
 {state&&<div className={css.notice}>{state.status==='Complete'?`${m!.extracted} original extractions · ${m!.reviewed} reviewed · ${m!.unreviewed} unreviewed`:state.status}<p className={styles.note}>{state.model?`${state.model} · Model execution · Completed ${state.finishedAt}`:state.status==='Failed'?state.error:'Extraction runs only when requested. This page refreshes while it is running.'}</p>{(state.status==='Failed'||state.status==='Running'&&run!.readAt-Date.parse(state.startedAt!)>300000)&&<ExtractionActions mode="retry" id={run!.id} revision={run!.revision}/>}</div>}
 {tab==='pages'?<section className={styles.panel}><h2>Source review</h2><p>Check the original pages for missed requirements. Reviewing only the AI’s answers does not establish that it found every term.</p>{source.pages.map(p=><details key={p.page}><summary>PDF page {p.page} · {state?.original.filter(r=>r.citations.some(c=>c.page===p.page)).length??0} extracted requirements · {state?.pageReviews.some(r=>r.page===p.page)?'Reviewed':'Not reviewed'}</summary><a href={`${source.localUrl}#page=${p.page}`} target="_blank" rel="noreferrer">Open original page ↗</a><pre className={css.trace}>{p.text}</pre>{state?.status==='Complete'&&<ExtractionActions key={`${p.page}-${run!.revision}`} mode="page" id={run!.id} revision={run!.revision} page={p.page}/>}</details>)}</section>:tab==='accuracy'?<section className={styles.panel}><h2>Original extraction accuracy</h2>{!m||state?.status!=='Complete'?<p>No completed model extraction to assess.</p>:<><div className={styles.metrics}>{[['Correct / reviewed',`${m.correct} / ${m.reviewed}`],['Reviewed accuracy',m.accuracy===null?'Not assessed':`${m.accuracy}%`],['Corrected answers',m.corrected],['Unsupported',m.unsupported],['Unverifiable',m.unverifiable],['Duplicates',m.duplicates],['Unreviewed',m.unreviewed],['Recorded omissions',m.omissions]].map(([label,v])=><article key={label}><span>{label}</span><strong>{v}</strong></article>)}</div><p className={styles.note}>Accuracy = original answers marked Correct ÷ all reviewed original answers. Corrections do not improve that score. Unreviewed answers are excluded, not assumed correct. Latest verdict counts; all prior decisions are retained.</p><p>{m.pagesReviewed} / {m.pagesInScope} supplied pages reviewed · {m.citationsMatched} / {m.extracted} extractions have matching quotations.</p><p className={styles.note}>Quotation matching verifies wording, not interpretation. Omission count reflects only what reviewers have found. No full-contract recall or completeness percentage is asserted.</p><h3>Missed requirements</h3>{state!.omissions.length?state!.omissions.map(o=><div key={o.id} className="my-4 rounded-lg border border-ink-100 p-4"><p>Page {o.page} · {o.interpretation}</p><blockquote>{o.quote}</blockquote><p className={styles.note}>{o.actor} · {o.at}</p></div>):<p>No omissions recorded. This is not evidence that none exist.</p>}<details><summary>Review history and execution record</summary><pre>{JSON.stringify({model:state!.model,usage:state!.usage,sourceHash:source.sha256,originalHash:state!.originalHash,attempt:state!.attempt,reviews:state!.reviews,pageReviews:state!.pageReviews},null,2)}</pre></details></>}</section>:<>
 {!state||state.status!=='Complete'?<section className={styles.panel}><h2>Review the AI’s work</h2><p>Extract requirements from the supplied pages, then inspect each source passage and interpretation. Nothing is approved automatically.</p></section>:<>
 <nav className={styles.recent} aria-label="Leakage areas"><Link href={url('requirements',undefined,'')}>All areas</Link>{AREAS.filter(a=>state.original.some(r=>r.area===a)).map(a=><Link key={a} href={url('requirements',undefined,a)} aria-current={area===a?'page':undefined}>{a}</Link>)}</nav>
 <section className={styles.panel}><details key={selected?.id}><summary>Choose a requirement · {filtered.length} available</summary>{filtered.length?<div className="mt-4 grid max-h-80 gap-2 overflow-y-auto md:grid-cols-2">{filtered.map(r=>{const verdict=state.reviews.findLast(v=>v.requirementId===r.id)?.verdict;return <Link key={r.id} className="rounded-lg border border-ink-100 p-3 text-sm" href={url('requirements',r.id)} aria-current={selected?.id===r.id?'page':undefined}><strong>{r.title}</strong><p>{r.area} · {verdict??'Unreviewed'}{!r.citations.every(c=>c.matched)?' · Citation mismatch':''}</p></Link>;})}</div>:<p>No requirements extracted in this area. Review the source pages for omissions.</p>}</details></section>
 {selected&&<section className={styles.panel}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>{selected.area} · {selected.id}</span><h2>{selected.title}</h2></div><span className={styles.badge}>{review?.verdict??'Unreviewed'}</span></div>
 <div className="grid items-start gap-6 lg:grid-cols-2"><section><h3>Original contract language</h3>{selected.citations.map((c,i)=>{const page=source.pages.find(p=>p.page===c.page),text=normalize(page?.text??'');return <div key={i} className="my-4 rounded-lg border border-ink-100 bg-ink-50 p-4"><a href={`${source.localUrl}#page=${c.page}`} target="_blank" rel="noreferrer">PDF page {c.page} ↗</a><p className={styles.note}>{c.matched?'Exact wording matched · Whitespace normalized':'Citation mismatch · Do not rely on this quotation'}</p>{c.matched?<p className="mt-3 leading-relaxed">{text.slice(Math.max(0,c.start-250),c.start)}<mark className="bg-amber-100">{text.slice(c.start,c.end)}</mark>{text.slice(c.end,c.end+250)}</p>:<blockquote>{c.quote}</blockquote>}<details><summary>Full extracted page</summary><pre className={css.trace}>{page?.text??'Page not supplied'}</pre></details></div>;})}</section>
 <section><h3>Original AI interpretation</h3><p>{selected.interpretation}</p><h3 className="mt-5">Conditions and exceptions</h3>{selected.conditions.length?<ul className={styles.list}>{selected.conditions.map((c,i)=><li key={i}>{c}</li>)}</ul>:<p>None identified by the AI.</p>}<h3 className="mt-5">Proposed implementation</h3><p>{selected.implementation}</p><h3 className="mt-5">Missing dependencies</h3>{selected.missingDependencies.length?<ul className={styles.list}>{selected.missingDependencies.map((d,i)=><li key={i}>{d}</li>)}</ul>:<p>None identified by the AI.</p>}<details><summary>Proposed verification cases · Not executed</summary>{selected.tests.map((t,i)=><div key={i} className="my-3"><p><strong>Input:</strong> {t.input}</p><p><strong>Expected:</strong> {t.expected}</p></div>)}</details></section></div>
 <div className="mt-6 border-t border-ink-100 pt-5"><h3>Your assessment</h3>{review&&<p className={styles.note}>Last verdict: {review.verdict} · {review.actor} · {review.at}</p>}{review?.correction&&<div className={css.notice}><strong>Reviewed interpretation</strong><p>{review.correction}</p></div>}<div className="mt-4 max-w-2xl"><ExtractionActions key={`${selected.id}-${run!.revision}`} mode="review" id={run!.id} revision={run!.revision} requirementId={selected.id} initialCorrection={review?.correction??selected.interpretation}/></div></div>
 </section>}
 <section className={styles.panel}><h2>Extraction limits</h2>{!state.limitations.length&&<p>No additional limitations recorded by the model. The selected-page scope and missing dependencies above still apply.</p>}<ul className={styles.list}>{state.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></section>
 </>}
 </>}
 <p className={styles.note}>Manual review evaluates AI accuracy. It does not activate client requirements. Drug lists, clinical criteria and later amendments must be obtained and reviewed before implementation.</p>
 </div>;
}
