'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export function ExtractionActions({id,revision=0,requirementId,page,mode='create',running=false,configured=true,initialCorrection=''}:{id?:string;revision?:number;requirementId?:string;page?:number;mode?:'create'|'review'|'page'|'retry';running?:boolean;configured?:boolean;initialCorrection?:string}){
 const router=useRouter(),pending=useRef<{signature:string;key:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verdict,setVerdict]=useState('Correct'),[correction,setCorrection]=useState(initialCorrection),[note,setNote]=useState(''),[quote,setQuote]=useState(''),[interpretation,setInterpretation]=useState('');
 useEffect(()=>{if(!running)return;const t=setInterval(()=>router.refresh(),5000);return()=>clearInterval(t)},[running,router]);
 async function send(action:string,fields:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');const body=action==='create'?{action}:{action,id,revision,...fields},signature=JSON.stringify(body);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};try{const r=await fetch('/api/contract-extraction',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,key:pending.current.key})});const data=await r.json();if(!r.ok)throw Error(data.error);pending.current=null;if(action==='create')router.push('/contract-extraction?run='+data.id);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 const button=(text:string,action:string,fields:Record<string,unknown>={})=><button disabled={busy||!configured} onClick={()=>send(action,fields)} className="rounded-lg border border-ink-200 bg-white px-4 py-2 text-xs font-medium disabled:opacity-50">{text}</button>;
 const field='mt-1 w-full rounded-lg border border-ink-200 bg-white p-3 text-sm';
 return <div className="space-y-3">{mode==='create'?<>{button('Extract with AI','create')}{!configured&&<p>Model connection required. No scripted extraction will be substituted.</p>}</>:mode==='retry'?button('Retry extraction','retry'):mode==='review'?<><label className="block text-xs">Your verdict<select className={field} value={verdict} onChange={e=>setVerdict(e.target.value)}><option>Correct</option><option>Corrected</option><option>Unsupported</option><option>Unverifiable</option><option>Duplicate</option></select></label>{verdict==='Corrected'&&<label className="block text-xs">Corrected interpretation<textarea className={field} rows={4} value={correction} onChange={e=>setCorrection(e.target.value)}/></label>}<label className="block text-xs">Review note<textarea className={field} rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label>{button('Save verdict','review',{requirementId,verdict,correction:verdict==='Corrected'?correction:'',note})}<p className="text-xs text-ink-500">Your verdict evaluates the original AI answer. It does not change live benefits or payments.</p></>:<>{button('Mark page reviewed','page',{page})}<details><summary>Add a missed requirement</summary><label className="mt-3 block text-xs">Exact passage<textarea className={field} rows={3} value={quote} onChange={e=>setQuote(e.target.value)}/></label><label className="block text-xs">Requirement the AI missed<textarea className={field} rows={3} value={interpretation} onChange={e=>setInterpretation(e.target.value)}/></label>{button('Record omission','omission',{page,quote,interpretation})}</details></>}{busy&&<p role="status" className="text-xs">Saving…</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
