import Link from 'next/link';
import {notFound} from 'next/navigation';
import {recentExtractions,readExtraction} from '@/lib/contract-extraction/service';
import {ExtractionActions} from './contract-extraction-actions';
import {ContractMappingForm} from './contract-mapping-form';
import {ContractSourceImage} from './contract-source-image';
import styles from './rebate-protection.module.css';
export async function ContractImplementationSetup({sponsor,extractionId,term}:{sponsor:string;extractionId?:string;term?:string}){
 const recent=await recentExtractions(sponsor);let extraction=extractionId?await readExtraction(extractionId,sponsor):null;if(extractionId&&!extraction)notFound();
 if(!extraction)for(const row of recent){const candidate=await readExtraction(row.id,sponsor);if(candidate?.state.status==='Complete'){extraction=candidate;break;}}
 const req=extraction?.state.original.find(r=>r.id===term)??extraction?.state.original.find(r=>r.area==='Prior authorization'&&r.citations.every(c=>c.matched))??extraction?.state.original[0];
 const review=extraction?.state.reviews.findLast(r=>r.requirementId===req?.id),ready=!!req&&req.citations.every(c=>c.matched)&&!!review&&['Correct','Corrected'].includes(review.verdict);
 return <section className={styles.panel}><span className={styles.eyebrow}>Contract implementation · Start here</span><h2>From contract to configuration</h2><p>Review the original clause, confirm the interpretation, then define the sandbox setting to test.</p>{!extraction||!req?<><p>No completed extraction is available for this sponsor.</p><Link href="/contract-extraction">Extract contract requirements →</Link></>:<>
 <details className="my-5"><summary>Choose a clause · {extraction.state.original.length} available</summary><div className="grid max-h-72 gap-2 overflow-auto py-3 sm:grid-cols-2">{extraction.state.original.map(r=><Link className="rounded-lg border border-ink-100 p-3 text-sm" key={r.id} href={`/rebate-protection?extraction=${extraction.id}&term=${r.id}`} aria-current={r.id===req.id?'page':undefined}>{r.title}<span className="block text-xs text-ink-500">{r.area}{r.citations.some(c=>!c.matched)?' · Citation mismatch':''}</span></Link>)}</div></details>
 <h3>{req.title}</h3><p className={styles.note}>{extraction.state.source.title} · Historical source, not current {sponsor} plan terms.</p>
 <div className="my-5 grid items-start gap-6 lg:grid-cols-2"><section><h3>1. Read the source</h3>{[...new Set(req.citations.map(c=>c.page))].map(page=><ContractSourceImage key={page} page={page} sha256={extraction.state.source.sha256}/>)}<details><summary>Quoted passages</summary>{req.citations.map((c,i)=><div key={i}><p>PDF page {c.page} · {c.matched?'Exact text matched':'Citation mismatch'}</p><blockquote>{c.quote}</blockquote></div>)}</details></section><section><h3>2. Review the interpretation</h3><p>{req.interpretation}</p>{req.conditions.length>0&&<><h4 className="mt-4 font-medium">Conditions</h4><ul className={styles.list}>{req.conditions.map((c,i)=><li key={i}>{c}</li>)}</ul></>}{req.missingDependencies.length>0&&<><h4 className="mt-4 font-medium">Missing evidence</h4><ul className={styles.list}>{req.missingDependencies.map((c,i)=><li key={i}>{c}</li>)}</ul></>}
 <div className="mt-5 rounded-lg border border-ink-100 p-4"><p className="mb-3 text-sm">Your verdict: {review?.verdict??'Not reviewed'}</p>{review?.correction&&<p className="mb-4">Reviewed interpretation: {review.correction}</p>}<ExtractionActions key={`${req.id}-${extraction.revision}`} mode="review" id={extraction.id} revision={extraction.revision} requirementId={req.id} initialVerdict={review?.verdict??'Correct'} initialCorrection={review?.correction??req.interpretation}/></div>
 <div className="mt-6 border-t border-ink-100 pt-5"><h3>3. Define the expected configuration</h3><p className="my-3"><strong>AI implementation proposal</strong><br/>{req.implementation}</p>{ready?<ContractMappingForm extractionId={extraction.id} extractionRevision={extraction.revision} requirementId={req.id}/>:<p>Record a Correct or Corrected verdict with matching source citations to continue. Unsupported, unreviewed or mismatched clauses cannot be implemented. <Link href={`/contract-extraction?run=${extraction.id}&term=${req.id}`}>Open extraction review →</Link></p>}</div></section></div>
 </>}</section>;
}
