"use client";
import { useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
export function DataCheckControls({id,index=0,total=0}:{id?:string;index?:number;total?:number}){
 const router=useRouter(),key=useRef<string|null>(null),stop=useRef(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(index),[custom,setCustom]=useState('');
 async function send(body:unknown){const r=await fetch('/api/data-agent-checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error??'Request failed');return data;}
 async function create(){setBusy(true);setError('');try{key.current??=crypto.randomUUID();const r=await send({action:'create',key:key.current,...(custom.trim()?{question:custom.trim()}:{})});key.current=null;router.push(`/data-agent-checks?run=${r.id}`);router.refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function run(){setBusy(true);setError('');stop.current=false;try{for(let i=index;i<total&&!stop.current;i++){await send({action:'next',id,index:i});setProgress(i+1);router.refresh();}}catch(e){setError(String(e));}finally{setBusy(false);router.refresh();}}
 return <div className="space-y-3">{!id?<><label className="block text-sm font-medium" htmlFor="custom-question">Optional custom question</label><textarea id="custom-question" maxLength={1000} value={custom} disabled={busy} onChange={e=>{setCustom(e.target.value);key.current=null;}} placeholder="Leave empty to run the 12-question test set" className="w-full rounded-lg border border-ink-200 p-3 text-sm"/><button disabled={busy} onClick={create} className="rounded-lg bg-ink-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?'Preparing…':custom.trim()?'Create question test':'Create test set'}</button></>:index<total?<div className="flex flex-wrap items-center gap-3"><button disabled={busy} onClick={run} className="rounded-lg bg-ink-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?`Running · ${progress}/${total}`:'Run remaining questions'}</button>{busy&&<button onClick={()=>{stop.current=true;}} className="text-sm underline">Stop after this answer</button>}<span className="text-sm text-ink-500">One question at a time. Resume from this page.</span></div>:<p className="text-sm text-ink-500">All answers recorded.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
