import Link from 'next/link';
import { notFound } from 'next/navigation';
import { selectedSponsor } from '@/lib/contract-checks/context';
import { getClock } from '@/lib/session';
import { readCheck,recentChecks } from '@/lib/data-checks/service';
import { outcome } from '@/lib/data-checks/evaluate';
import { DataCheckControls } from './data-check-controls';
export async function DataCheckPage({id}:{id?:string}){
 const sponsor=await selectedSponsor();
 if(sponsor!=='wisconsin')return <div className="space-y-5"><h1 className="text-3xl font-semibold">Data agent checks</h1><p>Tennessee has no connected data-agent claim book. Select Wisconsin to test the existing synthetic book.</p><Link href="/leakage-challenges">Open blind leakage challenges →</Link></div>;
 const clock=(await getClock()).now,run=id?await readCheck(id,clock):null;if(id&&!run)notFound();
 const recent=await recentChecks(clock),items=run?.items??[];
 const counts=[['Answers',items.length],['Checks passed',items.filter(i=>!i.error&&outcome(i.checks)==='Checks passed').length],['Needs review',items.filter(i=>!i.error&&outcome(i.checks)==='Needs review').length],['Failures',items.filter(i=>i.error||outcome(i.checks)==='Check failed').length]];
 return <div className="mx-auto max-w-6xl space-y-6"><header className="space-y-2"><p className="text-xs uppercase tracking-widest text-ink-500">Quality assurance · Scripted question tester</p><h1 className="text-3xl font-semibold tracking-tight">Data agent checks</h1><p className="text-sm text-ink-500">Questions, answers and evidence from the actual data agent.</p><div className="flex gap-5 text-sm"><Link href="/data-agent">Open data agent →</Link><Link href="/data-agent-checks">New test →</Link><Link href="/agents/data-agent-tester">Responsibilities →</Link></div></header>
 <section className="rounded-xl border border-ink-200 bg-white p-5"><p className="mb-4 text-sm text-ink-600">Uses the existing synthetic claim book, not actual Wisconsin or Tennessee member data. Test transcripts stay outside operational queues. Checks passed means the listed automated checks passed; factual accuracy still requires review.</p><DataCheckControls/></section>
 {recent.length>0&&<nav aria-label="Recent test runs" className="flex flex-wrap gap-3 text-xs">{recent.map(r=><Link className="rounded-full border border-ink-200 px-3 py-2" key={r.id} href={`/data-agent-checks?run=${r.id}`}>{r.createdAt.toISOString().replace('T',' ').slice(0,19)} UTC</Link>)}</nav>}
 {run&&<><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{counts.map(([label,n])=><div key={label} className="rounded-xl border border-ink-200 bg-white p-5"><p className="text-xs text-ink-500">{label}</p><p className="mt-2 text-3xl font-semibold">{n}</p></div>)}</section><section className="space-y-3 rounded-xl border border-ink-200 bg-white p-5"><p className="text-sm">Evidence cutoff {run.cutoff.toISOString()} · {items.length} of {run.cases.length} questions recorded</p><DataCheckControls key={run.id} id={run.id} index={items.length} total={run.cases.length}/><Link className="block text-sm" href={`/api/data-agent-checks?id=${run.id}`}>Export transcript →</Link><Link className="block text-sm" href={`/agents/runs/${run.id}`}>Work detail →</Link></section>
 <section className="overflow-hidden rounded-xl border border-ink-200 bg-white">{run.cases.map((test,index)=>{const item=items[index];return <details key={test.id} className="border-b border-ink-100 p-5 last:border-0"><summary className="cursor-pointer"><span className="text-xs text-ink-500">{index+1} · {test.category} · {item?(item.error?'Execution error':outcome(item.checks)):'Not run'}</span><span className="mt-1 block font-medium">{test.question}</span></summary><div className="mt-5 space-y-5">{item?.error?<p role="alert">{item.error}</p>:item?.answer?<><div className="space-y-3 rounded-lg bg-ink-50 p-4"><h2 className="text-xs font-semibold uppercase tracking-wide text-ink-500">Recorded answer</h2>{item.answer.paragraphs.map((p,i)=><p key={i} className="whitespace-pre-wrap text-sm leading-relaxed">{p}</p>)}</div><p className="text-xs text-ink-500">{item.answer.brain==='model'?'Model-assisted':'Scripted'} · {item.answer.elapsedMs.toLocaleString()} ms · Intent: {item.answer.intent} · {item.recordedAt}</p><div className="space-y-2">{item.checks.map((c,i)=><div key={i} className="rounded-lg border border-ink-100 p-3 text-sm"><strong>{c.label}</strong> · {c.status==='pass'?'Passed':c.status==='fail'?'Failed':'Review needed'}<p className="mt-1 text-ink-500">{c.detail}</p></div>)}</div><details><summary className="cursor-pointer text-sm">Tools and source evidence · {item.answer.work.length} calls</summary>{item.answer.work.map((w,i)=><div key={i} className="mt-3 space-y-2 text-sm"><h3 className="font-medium">{w.tool}</h3><p>{w.because}</p><p>{w.summary??w.error}</p><pre className="max-h-80 overflow-auto rounded-lg bg-ink-50 p-3 text-xs">{JSON.stringify({args:w.args,data:w.data,citations:w.citations},null,2)}</pre></div>)}</details></>:<p className="text-sm text-ink-500">This question has not been sent to the data agent.</p>}</div></details>;})}</section></>}
 </div>;
}
