'use client';
import {useState} from 'react';
import type {ReferenceResult} from '@/lib/drug-reference-checks/run';
export function DrugReferenceChecks(){
 const [result,setResult]=useState<ReferenceResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[all,setAll]=useState(false);
 async function run(){setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/drug-reference-checks',{method:'POST'});const data=await r.json();if(!r.ok)throw Error(data.error);setResult(data);}catch(e){setError(e instanceof Error?e.message:'Unable to run checks');}finally{setBusy(false);}}
 function download(){if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='public-drug-checks.json';a.click();URL.revokeObjectURL(url);}
 const rows=result?.outputs.filter(r=>(all||r.processing==='Processed'||r.issues.length)&&`${r.ndc11} ${r.description} ${r.manufacturer}`.toLowerCase().includes(query.toLowerCase()))??[];
 return <section id="public-drug-checks" className="my-6 rounded-xl border border-ink-200 bg-white p-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-ink-500">Public data · Technology demonstration</p><h3 className="mt-2 text-xl font-medium">Drug classification check</h3><p className="mt-2 max-w-2xl text-sm text-ink-600">Apply Tennessee’s single-source generic rule to 282 published Maine drug records. Inspect the source, expected category and produced result.</p></div><button disabled={busy} onClick={run} className="rounded-lg bg-ink-800 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?'Running…':result?'Run again':'Run checks'}</button></div>
  <p className="mt-3 text-xs text-amber-800">Historical Tennessee compliance remains unverified. No claims, configuration or payments change.</p>
  {error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
  {!result&&!busy&&<p className="mt-4 text-sm text-ink-500">Not run. Checks execute only when requested.</p>}
  {busy&&<p role="status" className="mt-4 text-sm">Checking source records and rule outputs…</p>}
  {result&&<><div aria-live="polite" className="my-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Source records',result.summary.records],['Rule cases passed',result.summary.verified],['Failed / blocked',`${result.summary.failed} / ${result.summary.blocked}`],['Outside this rule',result.summary.outsideRule]].map(([label,n])=><div key={label} className="rounded-lg bg-ink-50 p-4"><span className="text-xs text-ink-500">{label}</span><strong className="mt-1 block text-2xl font-medium">{n}</strong></div>)}</div>
   <p className="text-sm font-medium">{result.status==='Passed'?'The five defined rule cases passed.':'Some checks did not pass.'}</p><p className="mt-1 text-xs text-ink-500">Executed {result.executedAt.replace('T',' ').slice(0,19)} UTC · Deterministic processing · Results are held in this view; export to retain them.</p>
   <div className="my-5 flex flex-wrap items-center gap-4"><label className="text-sm">Find drug <input className="ml-2 rounded border border-ink-200 p-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="NDC or description"/></label><label className="text-sm"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> All source records</label><button onClick={download} className="text-sm underline">Export results</button></div>
   <p className="mb-3 text-xs text-ink-500">{rows.length} records shown. Expected results were transcribed separately from the published workbook; the processor does not read that answer list.</p>
   <div className="max-h-[560px] space-y-3 overflow-y-auto">{rows.map((r,i)=>{const v=result.verification.results.find(v=>v.ndc11===r.ndc11);return <details key={`${r.ndc11}-${i}`} className="rounded-lg border border-ink-200 p-4"><summary className="cursor-pointer text-sm"><strong>{r.description}</strong><span className="mt-1 block text-xs text-ink-500">{r.ndc11} · {r.issues.length?'Blocked':v?.status??'Not tested · Outside this rule'}</span></summary><div className="mt-4 grid gap-4 text-sm md:grid-cols-3"><div><strong>Source</strong><p>{r.manufacturer}</p><p>Report category: {r.reportCategory}</p><p>Source type: {r.publishedSourceType}</p><p>Workbook row {r.sourceRow}</p></div><div><strong>Expected</strong><p>{v?`${v.expectedBucket} guarantee category`:'Not assessed by this rule'}</p><p className="mt-2 text-xs text-ink-500">Single-source generics stay in the generic category for pricing and guarantee reconciliation.</p></div><div><strong>Produced</strong><p>{r.producedBucket??'No category produced'}</p><p>{r.processing}</p>{r.issues.map(x=><p key={x}>{x}</p>)}</div></div><p className="mt-4 text-xs text-amber-800">Classification effective date unavailable. No actual Tennessee claim or guarantee result is supplied for comparison.</p><details className="mt-3 text-xs"><summary>Original source cells</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap">{JSON.stringify(r.sourceCells,null,2)}</pre></details></details>;})}</div>
   {!rows.length&&<p className="text-sm">No matching records.</p>}
   <details className="mt-5 text-sm"><summary>Scope and evidence</summary><p className="mt-3">{result.source.provenance}</p><ul className="my-3 list-disc pl-5">{[...result.source.periodNotes,...result.limitations].map(t=><li key={t}>{t}</li>)}</ul><a className="underline" href={result.source.downloadUrl}>Original Maine workbook ↗</a><p className="mt-2 text-xs">Processor {result.processorVersion} · Verifier {result.verifierVersion} · Input digest {result.sourceSnapshotHash}</p></details>
  </>}
 </section>;
}
