'use client';
import {useEffect,useState} from 'react';
import {ContractPageViewer} from './contract-page-viewer';
import type {Run} from '@/lib/formulary-checks/service';
import type {Draft} from '@/lib/formulary-checks/processor';
import type data from '../../data/formulary-checks/tennessee.json';

type Source=typeof data;
const value=(v:unknown)=>v===true?'Listed':v===null?'Not listed':String(v);
const fields=[['classification','Drug label'],['tier','Tier'],['PA','Prior authorization'],['ST','Step therapy'],['QL','Quantity limit'],['SP','Specialty']] as const;
export function FormularyChecks({source,canReview}:{source:Source;canReview:boolean}){
 const [run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(source.rows[0].id),[note,setNote]=useState(''),[loaded,setLoaded]=useState(false);
 async function load(id?:string){const response=await fetch('/api/formulary-checks'+(id?'?id='+encodeURIComponent(id):''),{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error);setRun(body.run);setLoaded(true);}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoaded(true);});},[]);
 async function command(data:object){setBusy(true);setError('');try{const response=await fetch('/api/formulary-checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,key:crypto.randomUUID()})});const body=await response.json();if(!response.ok)throw Error(body.error);await load(body.id);setNote('');}catch(e){setError(e instanceof Error?e.message:'Unable to complete request');}finally{setBusy(false);}}
 const row=source.rows.find(r=>r.id===selected)!,produced=run?.state.outputs.find(o=>o.id===selected),test=run?.state.tests.find(t=>t.id===selected),review=run?.state.reviews.findLast(r=>r.rowId===selected);
 const latestReviews=new Map(run?.state.reviews.map(r=>[r.rowId,r]));
 const confirmed=[...latestReviews.values()].filter(r=>r.verdict==='Correct').length;
 const corrections=[...latestReviews.values()].filter(r=>r.verdict==='Needs correction').length;
 const rows=source.rows.filter(r=>`${r.name} ${r.cells.limits}`.toLowerCase().includes(query.toLowerCase()));
 const gaps=produced?[...(produced.PA||produced.ST?['Drug-specific clinical criteria not connected.']:[]),...(produced.QL?['Quantity threshold and time period not supplied by this row.']:[]),'NDC mapping and active PBM configuration not connected.']:[];
 function download(){if(!run)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({source,run,scope:'Selected published rows; no historical operations or claims tested'},null,2)],{type:'application/json'}));a.href=url;a.download='tennessee-formulary-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section id="formulary-checks" className="my-6 rounded-xl border border-ink-200 bg-white p-5 md:p-7">
  <div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-ink-500">Tennessee · Effective {source.effectiveDate}</p><h3 className="mt-2 text-2xl font-medium">Formulary to configuration</h3><p className="mt-2 max-w-2xl text-sm text-ink-600">Inspect a published drug row, generate its draft configuration, then review the result.</p></div><button disabled={busy||!canReview} onClick={()=>command({action:'create'})} className="self-start rounded-lg bg-ink-800 px-4 py-2.5 text-sm text-white disabled:opacity-50">{busy?'Working…':run?'New draft':'Generate & check'}</button></div>
  <p className="mt-3 text-xs text-ink-500">{source.rows.length} rows · Pages {source.selectedPages.join(', ')} of {source.totalPages} · Deterministic translation, not AI extraction · Draft only</p>
  {!canReview&&<p className="mt-3 text-sm text-amber-800">Historical view. Return to the current clock to generate or review.</p>}
  {error&&<p role="alert" className="my-3 text-sm text-red-700">{error} <button className="underline" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></p>}
  <div aria-live="polite" className="my-6 grid grid-cols-2 gap-3 lg:grid-cols-4">
   {[['Source','Connected'],['Reference tests',run?`${run.state.tests.filter(t=>t.status==='Passed').length} / ${run.state.tests.length} passed`:loaded?'Not run':'Loading…'],['Your review',`${confirmed} / ${source.rows.length} confirmed`],['Actual operations','Not connected']].map(([label,v])=><div key={label} className="rounded-lg bg-ink-50 p-4"><p className="text-xs text-ink-500">{label}</p><strong className="mt-2 block text-sm font-medium">{v}</strong></div>)}
  </div>
  {run&&<p className="mb-4 text-xs text-ink-500">Recorded {run.state.createdAt.replace('T',' ').slice(0,19)} UTC · {run.state.outputs.filter(o=>o.issues.length).length} blocked rows · {corrections} corrections requested. Twelve reference cases have separate expected answers; other rows need your review.</p>}
  <div className="flex flex-wrap items-end justify-between gap-3 border-t border-ink-100 pt-5"><label className="block text-sm">Find a drug<input className="mt-2 block w-full rounded-lg border border-ink-200 p-2 sm:w-72" placeholder="Name or restriction" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="flex gap-4 text-sm"><a className="underline" href={source.localUrl} target="_blank" rel="noreferrer">Full formulary ↗</a>{run&&<button onClick={download} className="underline">Export evidence</button>}</div></div>
  <div className="mt-5 grid items-start gap-6 lg:grid-cols-[240px_minmax(0,1fr)]">
   <nav aria-label="Published drug rows" className="max-h-64 space-y-1 overflow-auto rounded-lg border border-ink-200 p-2 lg:max-h-[680px]">{rows.map(r=><button key={r.id} aria-current={selected===r.id?'true':undefined} onClick={()=>{setSelected(r.id);setNote('');}} className={`block w-full rounded-md p-3 text-left text-xs ${selected===r.id?'bg-ink-800 text-white':'hover:bg-ink-50'}`}><span className="block font-medium">{r.name}</span><span className="mt-1 block opacity-70">Page {r.page} · {latestReviews.get(r.id)?.verdict??'Review pending'}</span></button>)}{!rows.length&&<p className="p-3 text-sm">No matching drugs.</p>}</nav>
   <div className="min-w-0"><h4 className="text-lg font-medium">{row.name}</h4><p className="mt-1 text-xs text-ink-500">Formulary row · PDF {row.page} · Not a guarantee classification or a 2022 audit result</p>
    <div className="mt-5 grid gap-6 xl:grid-cols-2"><div><p className="mb-2 text-xs font-medium text-ink-500">01 · Published source</p><ContractPageViewer label="Formulary" image={`/reference/tennessee/2026-10/page-${row.page}.png`} page={row.page} width={row.width} height={row.height} boxes={[row.box]}/><blockquote className="mt-3 rounded-lg bg-ink-50 p-3 text-xs"><p>{row.name}</p><p>Tier {row.cells.tier} · {row.cells.limits||'Restriction cell blank'}</p></blockquote><details className="mt-3 text-xs"><summary>Original extracted cells</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap">{JSON.stringify(row.cells,null,2)}</pre><p className="mt-2">Brand/generic labels are embedded in the PDF text; the printed guide uses typography. They do not establish contract guarantee eligibility.</p></details></div>
     <div><p className="mb-2 text-xs font-medium text-ink-500">02 · Generated configuration</p>{!produced?<p className="rounded-lg bg-ink-50 p-4 text-sm">Choose Generate & check to create the draft from these source cells.</p>:<><dl className="divide-y divide-ink-100">{fields.map(([k,label])=><div key={k} className="flex justify-between gap-3 py-2 text-sm"><dt className="text-ink-500">{label}</dt><dd>{value(produced[k as keyof Draft])}</dd></div>)}</dl><p className="mt-3 text-xs text-ink-500">“Not listed” preserves a blank field. It does not authorize a claim or disable a restriction.</p><div className="mt-5 rounded-lg bg-ink-50 p-4"><p className="text-xs font-medium">03 · Independent check</p><p className="mt-2 text-sm">{produced.issues.length?'Blocked':test?`${test.status} · Reference case`:'Not tested against a reference case'}</p>{test&&<details className="mt-2 text-xs"><summary>Expected values</summary><dl className="mt-2">{fields.map(([k,label])=><div key={k}>{label}: {value(test.expected[k])}</div>)}</dl>{test.differences.length>0&&<p>Differences: {test.differences.join(', ')}</p>}</details>}</div>{produced.issues.map(i=><p key={i} className="mt-2 text-sm text-red-700">{i}</p>)}<div className="mt-4 text-xs text-amber-800">{gaps.map(g=><p key={g} className="mt-1">{g}</p>)}</div></>}
     </div></div>
    {run&&produced&&<div className="mt-6 border-t border-ink-200 pt-5"><p className="text-xs font-medium text-ink-500">04 · Your review</p><p className="mt-2 text-sm">Compare the highlighted row with the draft. Confirming it records your review; it does not activate benefits.</p>{review&&<p className="mt-2 text-xs">{review.verdict} · {review.at.replace('T',' ').slice(0,19)} UTC · {review.actor}{review.note&&` · ${review.note}`}</p>}<label className="mt-4 block text-sm">Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} className="mt-2 block w-full rounded-lg border border-ink-200 p-3" rows={2}/></label><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy||!canReview||!!produced.issues.length||test?.status==='Failed'} className="rounded-lg bg-ink-800 px-4 py-2 text-sm text-white disabled:opacity-50" onClick={()=>command({action:'review',id:run.id,revision:run.revision,rowId:row.id,verdict:'Correct',note})}>Confirm row</button><button disabled={busy||!canReview||!note.trim()} className="rounded-lg border border-ink-200 px-4 py-2 text-sm disabled:opacity-50" onClick={()=>command({action:'review',id:run.id,revision:run.revision,rowId:row.id,verdict:'Needs correction',note})}>Needs correction</button></div></div>}
   </div>
  </div>
  <details className="mt-6 border-t border-ink-100 pt-4 text-xs text-ink-500"><summary>Scope and provenance</summary><p className="mt-3">Three selected pages are processed. The rest of the document is not tested. Reference cases were authored separately during development; no employee review is implied. Drafts do not supply NDC mapping, detailed clinical criteria, quantity thresholds, claim outcomes or financial results.</p><p className="mt-2">Source retrieved {source.retrievedOn} · SHA-256 <span className="break-all">{source.sha256}</span></p><a className="mt-2 block underline" href={source.url}>Publisher source ↗</a><a className="mt-2 block underline" href={source.localUrl+'#page=21'}>Definitions and source notices · PDF 21 ↗</a>{run&&<p className="mt-2 break-all">Run {run.id} · Output digest {run.state.outputHash}</p>}</details>
 </section>;
}
