import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getClock } from '@/lib/session';
import { selectedSponsor } from '@/lib/contract-checks/context';
import { PROFILES } from '@/lib/contract-checks/profiles';
import { readChallenge,recentChallenges } from '@/lib/leakage-challenge/service';
import { ChallengeControls } from './leakage-challenge-controls';
import { LeakageTests } from './leakage-tests';
import { formatCents } from '@/lib/money';
import styles from './rebate-protection.module.css';
const pct=(n:number|null)=>n===null?'—':`${(n*100).toFixed(1)}%`;
export async function ChallengePage({runId,tab='results',testId}:{runId?:string;tab?:string;testId?:string}){
 const sponsor=await selectedSponsor(),clock=await getClock();
 const run=runId?await readChallenge(runId,sponsor,clock.now):null;if(runId&&!run)notFound();
 const recent=await recentChallenges(sponsor,clock.now),report=run?.score;
 const base=`/leakage-challenges?${run?`run=${run.id}&`:''}`;
 return <div className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>{PROFILES[sponsor].name} · Quality assurance</span><h1>Blind challenges</h1><p className={styles.muted}>Introduce errors. Freeze findings. Compare the evidence.</p></div><span className={styles.badge}>Challenge agent · Scripted sandbox</span></header>
 <div className={styles.sectionHeading}><Link href="/contract-checks">← Leakage tests</Link><Link href="/rebate-protection">Eight-area detection & repair →</Link><Link href="/data-agent-checks">Data agent checks →</Link><Link href="/agents/leakage-challenge">Agent responsibilities →</Link></div>
 <ChallengeControls id={run?.id} scored={!!report}/>
 {recent.length>0&&<div className={styles.recent} aria-label="Recent challenges">{recent.map(r=><Link key={r.id} href={`/leakage-challenges?run=${r.id}`} aria-current={run?.id===r.id?'page':undefined}>{r.scoredAt?'Scored':'Prepared'} · {r.createdAt.toISOString().slice(5,19).replace('T',' ')} UTC</Link>)}</div>}
 {!run?<section className={styles.panel}><h2>Test the detector</h2><p>The challenge agent prepares a clean synthetic book, changes selected records and stores a private answer key. Glass receives only the altered files. A separate evaluator matches its frozen findings to the injected errors.</p><p>Each run includes clean records and can expose unsupported failure modes. A missed error remains visible. No real claims, payments or benefits are changed.</p></section>:<>
 <section className={styles.panel}><div className={styles.sectionHeading}><h2>{report?'Scoring complete':'Answer key withheld'}</h2>{report&&<div className="flex flex-wrap gap-4"><Link href={`/agents/runs/${run.id}`}>Work detail →</Link><a href={`/api/leakage-challenges?id=${run.id}`}>Export challenge →</a></div>}</div><p className={styles.muted}>Prepared {run.createdAt.slice(0,19).replace('T',' ')} UTC · Evidence cutoff {run.cutoff.slice(0,10)}{run.scoredAt?` · Scored ${run.scoredAt.slice(0,19).replace('T',' ')} UTC`:''}</p><p>{report?'Detector findings were frozen before comparison with the answer key. Results measure this challenge only.':'The detector has not run. Fault locations, types, amounts and the seed are not included in its input.'}</p><details><summary>Integrity and execution</summary><p>Input SHA-256: <span className="break-all">{run.inputHash}</span></p><p>Answer commitment: <span className="break-all">{run.commitment}</span></p><p>The salted answer hash was recorded before detection. The injector, detector and evaluator use separate code paths within this application; this is not an independent external audit or a security boundary against an application administrator.</p><p>Execution: deterministic · {run.detectorVersion??'Not yet executed'} · Financial authority: none.</p></details></section>
 {report&&<><div className={styles.metrics}><article><span>Injected errors</span><strong>{report.injected}</strong><small>{report.unquantified} without a dollar estimate</small></article><article className={styles.highlight}><span>Detected exactly</span><strong>{report.detected}</strong><small>{pct(report.exactRate)} · Correct type and amount</small></article><article><span>Missed</span><strong>{report.missed}</strong><small>{report.amountMismatches} additional amount mismatches</small></article><article><span>Unexpected alerts</span><strong>{report.falsePositives.length}</strong><small>Alerts with no matching injected error</small></article></div>
 <nav className={styles.tabs} aria-label="Challenge views">{[['results','Caught & missed'],['tests','Detector findings'],['method','Method & evidence']].map(([id,title])=><Link key={id} href={`${base}tab=${id}`} aria-current={tab===id?'page':undefined}>{title}</Link>)}</nav>
 {tab==='tests'&&run.result?<LeakageTests input={run.input} result={run.result} base={base} testId={testId}/>:tab==='method'?<section className={styles.panel}><h2>Scoring rules</h2><p>A hit requires the same claim and exception type. Exact detection also requires the expected amount, including an explicitly unquantified result. Each alert can match only one injected error. Different types are scored as a miss and an unexpected alert. Normal collection timing and contractual guarantee costs are observations, not error alerts.</p><div className={styles.delivery}><div><span>Detection rate</span><strong>{pct(report.detectionRate)}</strong></div><div><span>Alert precision</span><strong>{pct(report.precision)}</strong></div><div><span>Clean-claim false-positive rate</span><strong>{pct(report.falsePositiveRate)}</strong></div></div><p>{report.cleanClaimsFlagged} of {report.cleanClaims} clean claims incorrectly flagged. These rates apply only to the generated challenge; they are not estimates of production performance.</p><p>Fault types are scripted, but locations and amounts vary with a server-generated seed. Coverage-gap cases are included rather than removed to improve the score. Terms and rates are assumptions, not actual sponsor contracts. No savings or prevention is claimed.</p><details><summary>Reproducibility and revealed answer</summary><pre>{JSON.stringify(run.answer,null,2)}</pre></details><details><summary>Detector input</summary><pre>{JSON.stringify(run.input,null,2)}</pre></details></section>:<>
 <section className={styles.panel}><h2>Caught and missed</h2><p className={styles.muted}>The following errors were disclosed only after the detector completed. Amounts are test differences, not additive losses or savings.</p>{[...report.outcomes].sort((a,b)=>(a.status==='Missed'?0:a.status==='Amount mismatch'?1:2)-(b.status==='Missed'?0:b.status==='Amount mismatch'?1:2)).map(o=><details key={o.id}><summary className="flex flex-wrap justify-between gap-3"><strong>{o.name}</strong><span className={styles.testStatus} data-state={o.status==='Detected'?'Clear':'Exceptions'}>{o.status} · {o.amountCents===null?'Not quantified':formatCents(o.amountCents)}</span></summary><p>{o.why}</p><p className={styles.muted}>{o.claimId}</p><p><strong>Expected:</strong> {o.expectedKind} · {o.amountCents===null?'Not quantified':formatCents(o.amountCents)}</p><p><strong>Glass recorded:</strong> {o.finding?`${o.finding.kind} · ${o.finding.amountCents===null?'Not quantified':formatCents(o.finding.amountCents)}`:'No matching finding'}</p><p>{o.status==='Missed'?'This error escaped detection. Expand the control coverage and repeat the challenge.':o.status==='Amount mismatch'?'The exception type was detected, but the financial calculation needs review.':o.finding?.nextStep}</p><details><summary>Before and after records</summary><pre>{JSON.stringify({before:o.before,after:o.after,detector:o.finding},null,2)}</pre></details></details>)}</section>
 <section className={styles.panel}><h2>Unexpected alerts</h2>{report.falsePositives.length?report.falsePositives.map(f=><details key={f.id}><summary>{f.kind} · {f.claimId}</summary><p>No injected error matched this claim and exception type.</p><pre>{JSON.stringify(f,null,2)}</pre></details>):<p>No unmatched error alerts in this challenge. {report.cleanClaims} clean claims were included.</p>}</section>
 </>}
 <p className={styles.note}>Detection is not prevention. No correction, recovery, human approval or money movement was performed.</p>
 </>}
 </>}
 </div>;
}
