import Link from 'next/link';
import type { Evidence, Detection } from '@/lib/contract-checks/detector';
import { testInventory, COVERAGE_GAPS, findingEvidence } from '@/lib/contract-checks/inventory';
import { formatCents } from '@/lib/money';
import styles from './rebate-protection.module.css';
export function LeakageTests({input,result,base,testId}:{input:Evidence;result:Detection;base:string;testId?:string}){
 const tests=testInventory(input,result),selected=tests.find(t=>t.id===testId),gap=COVERAGE_GAPS.find(t=>t.id===testId);
 if(selected||gap){const t=selected??gap!;return <section className={styles.panel}>
  <Link href={`${base}tab=tests`}>← All tests</Link><div className={styles.sectionHeading}><h2 className="mt-5!">{t.name}</h2><span className={styles.testStatus} data-state={selected?.status}>{selected?.status??'Not connected'}</span></div><p>{t.rule}</p>
  {selected?<><p className={styles.muted}>{selected.evaluated} evaluated · {selected.blocked} blocked · {selected.pending} not yet due · {selected.findings.length} exceptions</p>
   {selected.blocked>0&&<p>Some records could not be evaluated. Resolve missing terms or source errors before treating this test as complete.</p>}
   {selected.findings.length===0&&<p>{selected.status==='Clear'?'No exceptions in the evaluated records.': 'No exception amount established for this population.'}</p>}
   {selected.findings.map(f=>{const evidence=findingEvidence(input,result.cutoff,f);return <article key={f.id} className="mt-6 border-t border-ink-200 pt-5">
    <div className={styles.sectionHeading}><h3>{f.kind==='Not verified'?'Eligibility or terms unavailable':f.kind}</h3><strong>{f.amountCents===null?'Not quantified':formatCents(f.amountCents)}</strong></div><p className={styles.muted}>{f.claimId} · {f.owner}</p>
    {evidence.comparison?<><p><strong>{evidence.comparison.label}</strong></p><div className={styles.delivery}><div><span>Expected</span><strong>{evidence.comparison.expected===null?'Not verified':formatCents(evidence.comparison.expected)}</strong></div><div><span>Recorded</span><strong>{formatCents(evidence.comparison.actual)}</strong></div><div><span>Difference</span><strong>{f.amountCents===null?'Not verified':formatCents(f.amountCents)}</strong></div></div>{evidence.comparison.deadline&&<p>Due {evidence.comparison.deadline.slice(0,10)} · Checked through {result.cutoff.slice(0,10)}</p>}</>:<p>The required evidence is missing, conflicting or duplicated. Glass cannot establish a reliable financial result.</p>}
    <p><strong>Next step</strong> · {f.nextStep}</p><p className={styles.note}>{f.category==='employer'?'Amount owed to the employer. Delivering it is not PBM savings.':f.category==='payment'?'Incorrect payment detected in synthetic records. No recovery recorded.':'Exposure or configuration difference. No settled recovery recorded.'}</p>
    <p className={styles.note}>Term: {evidence.term?.id??'Not verified'}<br/>{evidence.term?.citation}</p><details><summary>Supporting records</summary><pre>{JSON.stringify(evidence,null,2)}</pre></details>
   </article>;})}</>:<p>No pass result is available. Connect and validate the required source data before claiming coverage.</p>}
 </section>;}
 return <><section className={styles.panel}><div className={styles.sectionHeading}><h2>Detection tests</h2><span className={styles.badge}>Loaded synthetic records</span></div><p className={styles.muted}>Clear means no exception in the evaluated records. Integrity checks count source rows; financial checks count claims. Blocked and not-yet-due records remain outside the result.</p>
 <div className={styles.tableWrap}><table><thead><tr><th>Test</th><th>Result</th><th>Coverage</th><th>Exceptions</th><th>Amount</th></tr></thead><tbody>{tests.map(t=><tr key={t.id}><td><Link href={`${base}tab=tests&test=${t.id}`}><strong>{t.name} →</strong></Link></td><td><span className={styles.testStatus} data-state={t.status}>{t.status}</span></td><td>{t.evaluated} evaluated{t.blocked>0&&<small>{t.blocked} blocked</small>}{t.pending>0&&<small>{t.pending} not due</small>}</td><td>{t.findings.length}</td><td>{t.amountCents===null?'Not quantified':t.findings.length?formatCents(t.amountCents):'—'}</td></tr>)}</tbody></table></div><p className={styles.note}>Amounts represent different obligations and exposures. Do not add them together as savings.</p></section>
 <section className={styles.panel}><h2>Coverage still needed</h2><p>These controls are required for a broader assurance claim. They have no pass result.</p>{COVERAGE_GAPS.map(t=><div className="flex flex-wrap justify-between gap-3 border-t border-ink-100 py-4" key={t.id}><Link href={`${base}tab=tests&test=${t.id}`}>{t.name} →</Link><span className={styles.badge}>Not connected</span></div>)}</section></>;
}
