import Link from 'next/link';
import {notFound} from 'next/navigation';
import {selectedSponsor} from '@/lib/contract-checks/context';
import {getClock} from '@/lib/session';
import {readProcess,recentProcesses} from '@/lib/assurance/process/service';
import {STAGES,type Artifact} from '@/lib/assurance/process/types';
import {complete} from '@/lib/assurance/process/verifier';
import {terms} from '@/lib/assurance/process/processor';
import {ProcessActions} from './process-actions';
import base from './rebate-protection.module.css';
import css from './process-workspace.module.css';
const label=(k:string)=>k.replace(/Cents$/,'').replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
function Values({value}:{value:Artifact|null}){return !value?<p>Not produced</p>:<div className={css.value}><dl>{Object.entries(value).filter(([,v])=>typeof v!=='object'||v===null).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{v===null?'Not recorded':typeof v==='boolean'?v?'Yes':'No':typeof v==='number'&&k.endsWith('Cents')?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100):String(v)}</dd></div>)}</dl>{Object.entries(value).filter(([,v])=>v!==null&&typeof v==='object').map(([k,v])=><details key={k}><summary>{label(k)}{Array.isArray(v)?` · ${v.length}`:''}</summary><pre>{JSON.stringify(v,null,2)}</pre></details>)}</div>;}
export async function ProcessWorkspace({id,area,tab='process'}:{id?:string;area?:string;tab?:string}){
 const sponsor=await selectedSponsor(),clock=(await getClock()).now,recent=await recentProcesses(sponsor,clock),run=id?await readProcess(id,sponsor,clock):null;if(id&&!run)notFound();
 const state=run?.state,stage=STAGES.find(s=>s.id===area||String(s.area)===area)??STAGES[0],step=state?.steps[stage.id],selectedTerms=state?terms(state,stage.id):[];
 const href=(a:string=stage.id,t:string=tab)=>`/rebate-protection?${new URLSearchParams({...(run?{run:run.id}:{}),area:a,tab:t})}`;
 return <div className={base.page}>
 <header className={base.header}><div><span className={base.eyebrow}>{sponsor} · Operational leakage protection</span><h1>Leakage prevention</h1><p className={base.muted}>Follow the data. Inspect the result.</p></div><span className={base.badge}>Connected sandbox · Scripted execution</span></header>
 <div className={css.linked}><Link href="/contract-extraction">Contract extraction & review →</Link><Link href="/rebate-protection?tab=controls">Earlier controls & history →</Link><Link href="/contract-checks">Contract checks →</Link><Link href="/leakage-challenges">Blind challenges →</Link><Link href="/agents/rebate-protection">Agent responsibilities →</Link></div>
 <section className={base.panel}><div className={base.sectionHeading}><div><h2>Processing book</h2><p>Two synthetic claims, eight connected areas. Public definitions are cited; prices, rates and other terms are demo assumptions.</p></div><ProcessActions/></div>{run&&<><div className="my-5"><ProcessActions id={run.id} revision={run.revision}/></div><p className={base.note}>Evidence cutoff {state!.source.cutoff.slice(0,10)} · Revision {run.revision} · Last recorded {state!.events.at(-1)?.at??run.createdAt}</p><div className={css.linked}><Link href={href()}>Refresh</Link><Link href={`/api/operational-assurance/process?id=${run.id}`}>Export evidence</Link><Link href={`/agents/runs/${run.id}`}>Agent work</Link></div></>}</section>
 {recent.length>0&&<nav className={base.recent} aria-label="Recent process runs">{recent.map(r=><Link key={r.id} href={`/rebate-protection?run=${r.id}&tab=process&area=${stage.id}`}>{r.createdAt.toISOString().slice(0,19).replace('T',' ')} UTC</Link>)}</nav>}
 <nav className={base.tabs} aria-label="Leakage prevention views">{['process','tests','evidence'].map(t=><Link key={t} href={href(stage.id,t)} aria-current={tab===t?'page':undefined}>{label(t)}</Link>)}</nav>
 {state&&<div className={css.notice}>{complete(state)?'No unresolved discrepancies in the tested records.':`${Object.values(state.steps).filter(s=>s.status==='Released').length} of 8 areas released · Remaining gates and evidence shown below.`}<p className={base.note}>This result covers this synthetic population and these defined checks. It does not establish zero leakage across other records or future events.</p></div>}
 <div className={css.cards}>{[...STAGES].sort((a,b)=>a.area-b.area).map(s=>{const st=state?.steps[s.id];return <Link className={css.card} key={s.id} href={href(s.id)} aria-current={s.id===stage.id?'page':undefined}><span className={css.number}>0{s.area+1}</span><h2>{s.name}</h2><div><span className={css.status} data-state={st?.status}>{st?.status??'Not started'}</span></div><span className={css.counts}>{st?.checks.length??0} checks · {st?.checks.filter(c=>c.status==='Passed').length??0} passed<br/>{st?.status==='Blocked'?1:0} blocked step · {st?.checks.filter(c=>c.status==='Missing evidence').length??0} missing evidence<br/>{s.id==='claims'?Number(st?.output?.evaluated??0):st?.output?1:0} evaluated {s.id==='claims'?'claims':'artifact'}</span></Link>;})}</div>
 {!run?<section className={base.panel}><h2>{stage.name}</h2><p>{stage.rule}</p><p className={base.note}>Create a flow, then run a step. Outputs remain blocked until their checks and required reviews pass.</p></section>:tab==='tests'?<section className={base.panel}><h2>Tests</h2><p>Independent benchmark cases run in separate copies. Their approvals do not advance this book.</p>{!state!.tests?<p className={base.note}>Not tested · Select Run tests to record results.</p>:<><p className={base.note}>Recorded {state!.tests.at}</p>{state!.tests.cases.filter(c=>c.area===stage.id).map((c,i)=>{const status=c.passed?'Passed':c.name==='Selected run release'&&step?.status==='Missing evidence'?'Missing evidence':c.name==='Selected run release'&&step?.status!=='Failed'?'Blocked':'Failed';return <div className={css.test} key={i}><div><strong>{c.name}</strong><p>{c.detail}</p></div><span className={css.status} data-state={status}>{status}</span></div>;})}</>}</section>:tab==='evidence'?<section className={base.panel}><h2>Recorded evidence</h2><p>Actual recording times; simulated business events use the book’s cutoff.</p><ol className={base.timeline}>{state!.events.map((e,i)=><li key={i}><span>{e.at} · {e.actor}</span><h3>{e.kind}</h3><p>{e.step&&STAGES.find(s=>s.id===e.step)?.name} · {e.detail}</p></li>)}</ol><details><summary>Frozen inputs and versions</summary><pre>{JSON.stringify({hash:run.inputHash,versions:state!.versions,baseline:state!.baseline},null,2)}</pre></details><details><summary>Step attempts and artifact versions</summary><pre>{JSON.stringify(state!.steps,null,2)}</pre></details></section>:<section className={base.panel}>
 <div className={base.sectionHeading}><div><h2>{stage.name}</h2><p>{stage.role} · Responsible role</p></div><span className={css.status} data-state={step!.status}>{step!.status}</span></div>
 <ol className={css.flow}><li><a className={css.node} href="#flow-inputs"><strong>Source inputs</strong><span>{stage.dependencies.length?stage.dependencies.map(d=>STAGES.find(s=>s.id===d)!.name).join(' · '):'Effective contract requirements'}</span></a></li><li><a className={css.node} href="#flow-rule"><strong>Process</strong><span>{stage.id==='claims'?'Production adjudication engine':'Sandbox processor'} · version {step!.version}</span></a></li><li><a className={css.node} href="#flow-checks"><strong>Validation gate</strong><span>{step!.checks.filter(c=>c.status==='Passed').length} / {step!.checks.length} passed · {step!.status}</span></a></li><li><a className={css.node} href="#flow-output"><strong>Downstream output</strong><span>{step!.status==='Released'?'Available to dependent steps':'Not released'}</span></a></li></ol>
 <p id="flow-rule">{stage.rule}</p>
 <div className={css.comparison}><section><h3>Contract language</h3>{!selectedTerms.length?<p>Missing evidence · No effective source.</p>:selectedTerms.map(t=><div className={css.value} key={t.id}><p>{t.source?'Published definition · Synthetic financial terms':'Synthetic terms'}</p>{t.source&&t.source.recordedAt<=state!.source.cutoff?<><blockquote className="my-3 border-l-2 border-ink-200 pl-3">{t.source.text}</blockquote><p>{t.source.document} · {t.source.location}</p><a href={t.source.url} target="_blank" rel="noreferrer">Open source ↗</a></>:<p>Original contract text not loaded.</p>}<p>{t.clause} · v{t.version}<br/>{t.from} – {t.to}</p></div>)}</section><section><h3>Expected</h3><Values value={selectedTerms.length===1?selectedTerms[0].values:null}/><p className={base.note}>Effective requirements. Derived output comparisons appear in the validation gate.</p></section><section id="flow-output"><h3>Produced</h3><Values value={step!.output}/></section></div>
 <div id="flow-checks"><h3>Validation gate</h3>{!step!.checks.length?<p>Not tested{step!.status==='Blocked'?' · Upstream output unavailable':''}.</p>:step!.checks.map((c,i)=><details key={i}><summary>{c.name} · {c.status}</summary><div className="my-3 grid gap-4 sm:grid-cols-2"><div><h3>Expected</h3><pre>{JSON.stringify(c.expected,null,2)}</pre></div><div><h3>Produced</h3><pre>{JSON.stringify(c.produced,null,2)}</pre></div></div><p>{c.detail}</p></details>)}</div>
 <div className="my-5"><ProcessActions id={run.id} revision={run.revision} step={stage.id} state={step} repairable={!!state!.overrides[stage.id]&&step!.status==='Failed'}/></div>
 <div id="flow-inputs"><details><summary>Input records and upstream versions</summary><pre>{JSON.stringify(step!.attempts.at(-1)?.inputs??{dependencies:stage.dependencies,terms:selectedTerms},null,2)}</pre></details></div>
 <h3 className="mt-5">Next destination</h3><div className={css.linked}>{STAGES.filter(s=>s.dependencies.includes(stage.id)).map(s=><Link key={s.id} href={href(s.id)}>{s.name} →</Link>)}{!STAGES.some(s=>s.dependencies.includes(stage.id))&&<p>Sandbox evidence archive · No external release</p>}</div>
 </section>}
 <p className={base.note}>No real claims, benefits, rates, notices or payments change. Manufacturer acceptance, settlement and delivery are explicitly simulated.</p>
 </div>;
}
