'use client';
import {useEffect,useState,useRef} from 'react';
import {useSearchParams,useRouter,usePathname} from 'next/navigation';
import type {SourceRow,DraftRow,State} from '@/lib/public-data-checks/types';
import type sourceManifest from '../../data/public-data-checks/manifest.json';
import css from './public-data-checks.module.css';
type Row={id:string;area:string;kind:string;before:SourceRow|null;after:SourceRow|null;produced:DraftRow|null};
type Result={manifest:typeof sourceManifest;run:{id:string;revision:number;state:Omit<State,'draft'|'changes'>;changes:number;changeCounts:Record<string,number>}|null;rows:Row[];total:number;page:number;pages:number};
const names:Record<string,string>={formulary:'Formulary & UM',network:'Pharmacy network',benefits:'Cost sharing',insulin:'Insulin benefits',plan:'Plan terms',prices:'NADAC prices'};
export function PublicDataChecks({canRun}:{canRun:boolean}){
 const query=useSearchParams(),router=useRouter(),path=usePathname(),tab=query.get('tab')??'plan',area=tab==='prices'?'prices':query.get('area')??'formulary';
 const [loaded,setLoaded]=useState<{params:string;data:Result}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null),[search,setSearch]=useState(query.get('q')??''),[lookup,setLookup]=useState<{row:SourceRow|null;history:SourceRow[]}|null>(null);
 const [ndc,setNdc]=useState(''),[unit,setUnit]=useState('EA'),[asOf,setAsOf]=useState('2026-09-30'),[effective,setEffective]=useState('2026-09-30');
 const params=query.toString(),data=loaded?.params===params?loaded.data:null;
 const [refreshCount,setRefreshCount]=useState(0),detailRef=useRef<HTMLElement>(null);
 const refresh=()=>setRefreshCount(n=>n+1);
 const navigate=(values:Record<string,string>)=>{const p=new URLSearchParams(params);Object.entries(values).forEach(([k,v])=>v?p.set(k,v):p.delete(k));router.replace(`${path}?${p}`,{scroll:false});setSelected(null);};
 useEffect(()=>{
  const controller=new AbortController(),p=new URLSearchParams(params);if(p.get('tab')==='prices')p.set('area','prices');
  fetch('/api/public-data-checks?'+p,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!controller.signal.aborted){setLoaded({params,data:d});setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});
  return()=>controller.abort();
 },[params,refreshCount]);
 useEffect(()=>{if(selected){detailRef.current?.scrollIntoView({block:'start',behavior:'smooth'});detailRef.current?.focus({preventScroll:true});}},[selected]);
 async function act(action:'create'|'build'|'verify'){
  setBusy(true);setError('');try{const body=action==='create'?{action,key:crypto.randomUUID()}:{action,key:crypto.randomUUID(),id:data!.run!.id,revision:data!.run!.revision};const r=await fetch('/api/public-data-checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);navigate({id:d.id});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function lookupPrice(){setBusy(true);setError('');try{const r=await fetch('/api/public-data-checks?'+new URLSearchParams({ndc,unit,asOf,effective}));const d=await r.json();if(!r.ok)throw Error(d.error);setLookup(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const run=data?.run,stage=run?.state.stage,checks=run?.state.checks??[];
 return <main className={css.page}>
  <a href="/rebate-protection" className={css.back}>← Operational assurance</a>
  <header className={css.header}><div><p className={css.eyebrow}>Public source example · Medicare Part D</p><h1>Published data. Verified drafts.</h1><p>SilverScript Choice · S5601-024-000 · Alabama and Tennessee</p></div><button onClick={refresh} disabled={busy}>Refresh</button></header>
  <p className={css.notice}>A separate Medicare example, not the Tennessee employer contract. Real published records; isolated draft configuration. No claims, payments or savings are represented.</p>
  <nav className={css.tabs} aria-label="Public data views">{[['plan','Plan changes'],['prices','Price history'],['evidence','Evidence']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>navigate({tab:id,page:'1',q:''})}>{label}</button>)}</nav>
  {error&&<p role="alert" className={css.error}>{error}</p>}
  {!canRun&&<p className={css.notice}>Historical clock selected. Return to the current clock to record a run.</p>}
  {!data&&!error&&<p role="status">Loading source records…</p>}
  {data&&<>
   {tab==='plan'&&<>
    <section className={css.flow} aria-label="Processing steps">
     <div><span>01 · Compare</span><h2>August → September 2026</h2><p>Compare published fields. Formulary version metadata is retained as evidence, not counted as a clinical change.</p><button disabled={busy||!canRun} onClick={()=>act('create')}>{run?'Start new comparison':'Compare snapshots'}</button>{run&&<strong>{run.changes.toLocaleString()} record changes</strong>}</div>
     <div><span>02 · Build</span><h2>Update the draft</h2><p>Apply additions, changes and removals to the August draft. Published values stay exact.</p><button disabled={busy||!canRun||stage!=='Compared'} onClick={()=>act('build')}>Build updated draft</button>{stage&&stage!=='Compared'&&<strong>Draft recorded</strong>}</div>
     <div><span>03 · Verify</span><h2>Check every selected field</h2><p>Independently compare the produced draft with September source rows and import totals.</p><button disabled={busy||!canRun||!stage||stage==='Compared'} onClick={()=>act('verify')}>Verify draft</button>{stage==='Verified'&&<strong>{checks.filter(c=>c.status==='Passed').length} passed · {checks.filter(c=>c.status==='Failed').length} failed · {checks.filter(c=>c.status==='Missing evidence').length} gaps</strong>}</div>
    </section>
    <div className={css.areaGrid}>{Object.entries(names).filter(([a])=>a!=='prices').map(([a,label])=><button key={a} className={css.area} aria-pressed={area===a} onClick={()=>navigate({area:a,page:'1',q:''})}><span>{label}</span><strong>{(data.manifest.census['2026-09'] as Record<string,number>)[a]?.toLocaleString()??'0'}</strong><small>{run?`${run.changeCounts[a]??0} changes`:'September records'}</small></button>)}</div>
    {area==='network'&&<p className={css.notice}>{data.manifest.networkScope} These checks do not establish network adequacy.</p>}
    {area==='formulary'&&<p className={css.note}>NDCs are CMS proxy NDCs. PA, step therapy and quantity-limit flags are included; full clinical criteria are unavailable. Removal means absent from the later file, not proof of a member’s loss of coverage.</p>}
   </>}
   {tab==='prices'&&<section className={css.panel}><p className={css.eyebrow}>NADAC · August 26 and September 30, 2026</p><h2>Dated acquisition-cost references</h2><p>{data.manifest.prices.toLocaleString()} published price records matched to this plan’s proxy NDCs. This is not the plan’s contracted reimbursement basis.</p><form className={css.filters} onSubmit={e=>{e.preventDefault();lookupPrice();}}><label>NDC<input value={ndc} onChange={e=>setNdc(e.target.value)} placeholder="11 digits" pattern="[0-9]{11}" required/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}>{['EA','ML','GM'].map(x=><option key={x}>{x}</option>)}</select></label><label>Available as of<input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)} required/></label><label>Effective on<input type="date" value={effective} onChange={e=>setEffective(e.target.value)} required/></label><button disabled={busy}>Check dated price</button></form>{lookup&&<div role="status" className={css.notice}>{lookup.row?<><strong>${lookup.row.values['NADAC Per Unit']} / {lookup.row.values['Pricing Unit']}</strong><p>{lookup.row.values['NDC Description']} · Effective {lookup.row.values['Effective Date']} · Published snapshot {lookup.row.values['As of Date']} · CSV line {lookup.row.line}</p></>:<strong>No eligible price in the two imported snapshots.</strong>}<p>Uses both publication and effective dates. No interpolation or substitution for missing dates, NDCs or units.</p></div>}</section>}
   {tab==='evidence'?<>
    <section className={css.panel}><h2>Recorded work</h2>{run?<><p>{run.id} · Revision {run.revision} · {run.state.engine} · {run.state.verifier}</p><ol>{run.state.events.map((e,i)=><li key={i}>{e.action} · {new Date(e.at).toLocaleString()}</li>)}</ol><a href={`/api/public-data-checks?id=${run.id}&export=1`}>Download complete evidence</a></>:<p>Start a comparison to record processing and verification.</p>}</section>
    <section className={css.panel}><h2>Sources and scope</h2><p>Retrieved {new Date(data.manifest.retrievedAt).toLocaleString()}. Monthly snapshot names and internal month-end filenames are retained; neither establishes the exact date of a coverage change.</p><p><a href={data.manifest.dictionary} target="_blank" rel="noreferrer">CMS field definitions ↗</a></p><p>Cost type 1 = copay; 2 = coinsurance; 0 = not offered. Coinsurance values are decimal fractions. Days-supply codes: 1 = 30 days, 2 = 90 days, 3 = other, 4 = 60 days. Raw codes remain visible.</p>{data.manifest.sources.map(s=><details key={s.id}><summary>{s.period} · {s.file} · {s.selected.toLocaleString()} selected rows</summary><p>{s.scanned.toLocaleString()} source rows scanned. Exact source line numbers are preserved.</p><p><a href={s.url} target="_blank" rel="noreferrer">Original CMS download ↗</a></p><code>SHA-256 {s.sha256} · Hash applies to {s.hashFile}</code></details>)}</section>
   </>:<section className={css.panel}>
    <div className={css.sectionHead}><h2>{names[area]??area}</h2><span>{data.total.toLocaleString()} records</span></div>
    <form className={css.filters} onSubmit={e=>{e.preventDefault();navigate({q:search,page:'1'});}}><label>Search source records<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={area==='prices'?'Drug name or NDC':'NDC, pharmacy or field value'}/></label><button>Search</button>{tab==='plan'&&<label className={css.checkbox}><input type="checkbox" checked={query.get('all')==='1'} onChange={e=>navigate({all:e.target.checked?'1':'',page:'1'})}/>Include unchanged</label>}</form>
    {!data.rows.length&&<p>{run?'No matching changes. Include unchanged records to review the full selected population.':'Compare snapshots, or include unchanged records to inspect the sources.'}</p>}
    <div className={css.rows}>{data.rows.map(r=><button key={r.id} className={css.row} onClick={()=>{setSelected(r);if(area==='prices'){setNdc(r.after!.values.NDC);setUnit(r.after!.values['Pricing Unit']);}}}><span><strong>{area==='prices'?r.after!.values['NDC Description']:r.id.split(':').slice(1).join(' · ')}</strong><small>{area==='prices'?`${r.after!.values.NDC} · ${r.after!.values['As of Date']} · $${r.after!.values['NADAC Per Unit']}/${r.after!.values['Pricing Unit']}`:r.area==='formulary'?`Tier ${(r.after??r.before)!.values.TIER_LEVEL_VALUE} · PA ${(r.after??r.before)!.values.PRIOR_AUTHORIZATION_YN} · ST ${(r.after??r.before)!.values.STEP_THERAPY_YN}`:names[r.area]}</small></span><span>{r.kind} →</span></button>)}</div>
    <div className={css.pagination}><button disabled={data.page<=1} onClick={()=>navigate({page:String(data.page-1)})}>Previous</button><span>Page {data.page} of {data.pages}</span><button disabled={data.page>=data.pages} onClick={()=>navigate({page:String(data.page+1)})}>Next</button></div>
   </section>}
   {selected&&<section ref={detailRef} tabIndex={-1} className={css.panel} aria-label="Selected record evidence"><div className={css.sectionHead}><h2>{selected.id}</h2><button onClick={()=>setSelected(null)}>Close details</button></div><div className={css.evidenceGrid}>{[['August source',selected.before],['September source / expected',selected.after],['Produced draft',selected.produced]].filter((_,i)=>area!=='prices'||i===1).map(([label,row])=><div key={label as string}><h3>{area==='prices'?'Published source':label as string}</h3>{row?<><p>{'source' in (row as SourceRow)?`${(row as SourceRow).source} · Line ${(row as SourceRow).line}`:'Isolated configuration draft'}</p><dl>{Object.entries((row as SourceRow).values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v.trim()||'Blank in source'}</dd></div>)}</dl></>:<p>{label==='Produced draft'?stage==='Compared'||!stage?'Not built':'Absent from updated draft':'Absent from this snapshot'}</p>}</div>)}</div></section>}
   {!!checks.length&&<section className={css.panel}><h2>Verification results</h2><p>Passing source-agreement checks proves selected draft fields match published records. It does not establish correct claim payment or zero operational leakage.</p>{checks.map(c=><details key={c.name}><summary><span className={css.status}>{c.status}</span> {c.name} · {c.count.toLocaleString()} records</summary><p>{c.detail}</p></details>)}</section>}
  </>}
 </main>;
}
