'use client';
import {useEffect,useState,useRef} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import type {Book,Claim,Member,Journal,META} from '@/lib/realistic-book/core';
import type {summary} from '@/lib/realistic-book/service';
import css from './realistic-book.module.css';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
type Data={run:{id:string;createdAt:string;cutoff:string}|null;meta:typeof META;summary:ReturnType<typeof summary>;claims:Claim[];total:number;page:number;pages:number;members:(Member&{claims:number})[];rebates:Book['rebates'];checks:Book['checks'];balances:Record<string,number>;journal:Journal[];journalCount:number;journalPage:number;journalPages:number;invoices:{period:string;amount:number;paid:number}[];selected:{claim:Claim;member:Member;history:Claim[];journal:Journal[];rebate:Book['rebates'][number]|null}|null};
export function RealisticBook({canRun}:{canRun:boolean}){
 const q=useSearchParams(),router=useRouter(),params=q.toString(),view=q.get('view')??'overview';
 const [loaded,setLoaded]=useState<{params:string;data:Data}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(q.get('q')??''),[refresh,setRefresh]=useState(0);const data=loaded?.params===params?loaded.data:null;
 useEffect(()=>{const controller=new AbortController();fetch('/api/realistic-book?'+params,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setLoaded({params,data:d});setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[params,refresh]);
 function nav(values:Record<string,string>){const p=new URLSearchParams(params);for(const [k,v] of Object.entries(values))if(v)p.set(k,v);else p.delete(k);router.replace('/operating-demo?'+p,{scroll:false});}
 async function generate(){setBusy(true);setError('');try{const r=await fetch('/api/realistic-book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:crypto.randomUUID()})}),d=await r.json();if(!r.ok)throw Error(d.error);nav({id:d.id,claim:'',page:'1'});setRefresh(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const selected=data?.selected,detailRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(selected){detailRef.current?.scrollIntoView({behavior:'smooth',block:'start'});detailRef.current?.focus({preventScroll:true});}},[selected]);
 const filters=<form className={css.filters} onSubmit={e=>{e.preventDefault();nav({q:search,page:'1',jp:'1'});}}><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Claim, member, drug or NDC"/></label><label>Month<select value={q.get('month')??''} onChange={e=>nav({month:e.target.value,page:'1',jp:'1'})}><option value="">All months</option>{Array.from({length:9},(_,i)=><option key={i}>2026-{String(i+1).padStart(2,'0')}</option>)}</select></label>{view==='claims'&&<><label>Status<select value={q.get('status')??''} onChange={e=>nav({status:e.target.value,page:'1'})}><option value="">All statuses</option>{['Paid','Rejected','Reversal','Not verified'].map(s=><option key={s}>{s}</option>)}</select></label><label>Channel<select value={q.get('channel')??''} onChange={e=>nav({channel:e.target.value,page:'1'})}><option value="">All channels</option>{['Retail','Mail','Specialty'].map(s=><option key={s}>{s}</option>)}</select></label></>}<button>Search</button><button type="button" onClick={()=>{setSearch('');nav({q:'',month:'',status:'',channel:'',page:'1',jp:'1'});}}>Clear</button></form>;
 return <div className={css.page}><header className={css.header}><div><p className={css.eyebrow}>Cedar Works · Synthetic employer book</p><h1>Every claim, connected.</h1><p>240 covered lives. Nine months. Every transaction connected.</p></div><div className={css.links}><a href="/operating-demo?legacy=1">Guided correction →</a><a href="/versions">Versions →</a></div></header>
 <p className={css.notice}>Synthetic members, prescriptions, coverage and financial terms. Real drug identifiers and dated public NADAC references. Behaviorally varied, not calibrated to an actual employer or validated for clinical appropriateness.</p>
 <nav className={css.tabs} aria-label="Employer book">{['overview','claims','members','money','checks','sources'].map(v=><button key={v} aria-current={v===view?'page':undefined} onClick={()=>nav({view:v,claim:'',page:'1',jp:'1'})}>{v==='claims'?'Claims ledger':v==='money'?'Financial ledger':v[0].toUpperCase()+v.slice(1)}</button>)}</nav>
 {error&&<p role="alert" className={css.error}>{error}</p>}{!data&&!error&&<p role="status">Loading book…</p>}
 {data&&!data.run&&<section className={css.hero}><div><h2>Nine months of connected activity.</h2><p>Generate retail, mail and specialty fills, eligibility changes, prior-authorization resubmissions, accumulators, reversals and financial reconciliation.</p><p>No real member or payment records change.</p></div><button disabled={busy||!canRun} onClick={generate}>{busy?'Generating…':'Generate employer book'}</button></section>}
 {data?.run&&<><div className={css.toolbar}><span>January–September 2026 · Financial cutoff {data.run.cutoff}</span><div><button onClick={()=>setRefresh(n=>n+1)}>Refresh</button> <a href={`/api/realistic-book?id=${data.run.id}&export=1`}>Export full book ↗</a></div></div>
 <section className={css.metrics}><div><span>Net paid fills</span><strong>{data.summary.netFills.toLocaleString()}</strong><small>{data.summary.paid} paid · {data.summary.reversals} reversed</small></div><div><span>Net allowed cost</span><strong>{money(data.summary.allowed)}</strong><small>Public benchmark + synthetic channel fee</small></div><div><span>Member liability</span><strong>{money(data.summary.member)}</strong><small>Paid at pharmacy in this simulation</small></div><div><span>Employer claim cost</span><strong>{money(data.summary.employer)}</strong><small>Before admin fees, rebates and top-ups</small></div></section>
 {view==='overview'&&<><section className={css.hero}><div><p className={css.eyebrow}>Follow the records</p><h2>From the prescription to the invoice.</h2><p>{data.summary.submissions.toLocaleString()} submissions from {data.summary.users} utilizers. {data.summary.members-data.summary.users} members have no paid fills. Rejections, resubmissions and reversals remain visible.</p></div><button onClick={()=>nav({view:'claims'})}>Open all claims →</button></section><div className={css.cards}>{[['claims','Claims ledger','Search every submission. Open the price, benefit calculation, accumulator and financial entries.'],['members','Member history','Review enrollment, plan and a longitudinal sequence of fills for each member.'],['money','Financial ledger','Monthly invoices, quarterly rebate positions and balanced debit/credit entries.'],['checks','Verification','Inspect calculations, source dates, net populations and reconciliation checks.']].map(([v,title,description])=><button key={v} onClick={()=>nav({view:v})}><h2>{title}</h2><p>{description}</p><span>Explore →</span></button>)}</div><p className={css.note}>The guided 100-claim correction scenario remains a separate historical demonstration. This larger book has its own records and ledger; corrections from the older scenario are not applied here.</p></>}
 {view==='claims'&&<section className={css.panel}><h2>All claims</h2>{filters}<div className={css.tableWrap}><table><thead><tr>{['Claim / service date','Member','Drug / NDC','Channel','Status','Allowed','Member','Employer'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.claims.map(c=><tr key={c.id}><td><button className={css.record} onClick={()=>nav({claim:c.id})}>{c.id}</button><small>{c.date}</small></td><td>{c.memberId}</td><td>{c.drug}<small>{c.ndc} · {c.quantity} {c.unit} · {c.days} days</small></td><td>{c.channel}</td><td>{c.status}<small>{c.reason}</small></td><td>{money(c.allowed)}</td><td>{money(c.member)}</td><td>{money(c.employer)}</td></tr>)}</tbody></table></div>{!data.claims.length&&<p>No claims match these filters.</p>}<div className={css.pagination}><button disabled={data.page<=1} onClick={()=>nav({page:String(data.page-1),claim:''})}>Previous</button><span>{data.total} records · Page {data.page} of {data.pages}</span><button disabled={data.page>=data.pages} onClick={()=>nav({page:String(data.page+1),claim:''})}>Next</button></div></section>}
 {selected&&view==='claims'&&<section ref={detailRef} tabIndex={-1} className={css.panel} id="claim-detail"><div className={css.toolbar}><h2>{selected.claim.id} · {selected.claim.status}</h2><button onClick={()=>nav({claim:''})}>Close</button></div><p>{selected.claim.drug} · {selected.claim.reason||'Paid under the synthetic benefit'}</p><div className={css.cards}><div><h3>Source price</h3><p>{selected.claim.price?`${selected.claim.price.rate} USD/${selected.claim.unit} × ${selected.claim.quantity}, plus channel fee. Snapshot ${selected.claim.price.asOf}; effective ${selected.claim.price.effective}; source CSV line ${selected.claim.price.line}.`:'No applicable source reference.'}</p><a href={data.meta.source}>Original NADAC file ↗</a></div><div><h3>Benefit and enrollment</h3><p>{selected.member.plan} · Covered {selected.member.start} through {selected.member.end??'open enrollment end'}.</p><p>{selected.claim.pa}. Member {money(selected.claim.member)}; employer {money(selected.claim.employer)}.</p></div><div><h3>Individual accumulators</h3><p>Deductible: {money(selected.claim.deductibleBefore)} → {money(selected.claim.deductibleAfter)}</p><p>Out of pocket: {money(selected.claim.oopBefore)} → {money(selected.claim.oopAfter)}</p></div><div><h3>Reconciliation</h3><p>{selected.claim.settlementDate?`Synthetic pharmacy remittance ${selected.claim.settlementDate}`:'No remittance recorded for this submission.'}</p><p>{selected.rebate?`${selected.rebate.period} batch · ${selected.rebate.status}. Claim rebate entitlement ${money(selected.claim.rebate)}. Receipts are batch totals, not claim-specific payment confirmation.`:'No manufacturer rebate entitlement for this record.'}</p></div></div>{selected.claim.originalId&&<button onClick={()=>nav({claim:selected.claim.originalId!})}>Original submission {selected.claim.originalId} →</button>}<h3>Linked financial entries</h3>{selected.journal.map(j=><p key={j.id}>{j.date} · {j.description} · {j.lines.map(l=>`${l.account}: Dr ${money(l.debit)} / Cr ${money(l.credit)}`).join(' · ')}</p>)}<details><summary>Member’s full claim history · {selected.history.length} submissions</summary>{selected.history.map(c=><p key={c.id}><button onClick={()=>nav({claim:c.id})}>{c.id}</button> {c.date} · {c.drug} · {c.status} · {money(c.member)}</p>)}</details></section>}
 {view==='members'&&<section className={css.panel}><h2>Covered lives</h2><p>Fictional identifiers and ages. Household links are retained; benefit accumulators are individual only.</p><div className={css.tableWrap}><table><thead><tr>{['Member','Household','Age / relationship','Plan','Coverage','Submissions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.members.map(m=><tr key={m.id}><td><button className={css.record} onClick={()=>{setSearch(m.id);nav({view:'claims',q:m.id,status:'',channel:'',month:'',page:'1'});}}>{m.id}</button></td><td>{m.household}</td><td>{m.age} · {m.relationship}</td><td>{m.plan}</td><td>{m.start} → {m.end??'Open'}</td><td>{m.claims}</td></tr>)}</tbody></table></div></section>}
 {view==='money'&&<><section className={css.panel}><h2>Monthly employer invoices</h2><p>Net employer claim liability + fees − rebate credits and PBM-funded top-ups. Member copays are paid directly to the pharmacy and are not PBM cash receipts.</p><div className={css.tableWrap}><table><thead><tr><th>Service/posting month</th><th>Net invoice</th><th>Employer payment</th><th>Outstanding</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.period}><td>{i.period}</td><td>{money(i.amount)}</td><td>{money(i.paid)}</td><td>{money(i.amount-i.paid)}</td></tr>)}</tbody></table></div></section><section className={css.panel}><h2>Quarterly rebate position</h2><div className={css.tableWrap}><table><thead><tr>{['Period / due','Manufacturer entitlement','Received','Client top-up','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.rebates.map(r=><tr key={r.id}><td>{r.period}<small>{r.due}</small></td><td>{money(r.entitlement)}</td><td>{money(r.manufacturerReceived)}</td><td>{money(r.topup)}</td><td>{r.status}</td></tr>)}</tbody></table></div><p className={css.note}>Quarter-two receipts are deliberately partial. The full due employer credit is preserved. Quarter-three amounts are accrued, not settled; guarantee top-ups remain expected until reconciliation.</p></section><section className={css.panel}><h2>Double-entry journal</h2>{filters}<p>{data.journalCount.toLocaleString()} matching entries · Debits and credits shown separately. Synthetic cash confirmations, not bank records.</p><div className={css.tableWrap}><table><thead><tr>{['Date / transaction','Claim or batch','Account','Debit','Credit'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.journal.flatMap(j=>j.lines.map((l,i)=><tr key={j.id+i}><td>{j.date}<small>{j.description} · {j.id}</small></td><td>{j.claimId?<button className={css.record} onClick={()=>nav({view:'claims',claim:j.claimId!})}>{j.claimId}</button>:j.batch}</td><td>{l.account}</td><td>{money(l.debit)}</td><td>{money(l.credit)}</td></tr>))}</tbody></table></div><div className={css.pagination}><button disabled={data.journalPage<=1} onClick={()=>nav({jp:String(data.journalPage-1)})}>Previous</button><span>Page {data.journalPage} of {data.journalPages}</span><button disabled={data.journalPage>=data.journalPages} onClick={()=>nav({jp:String(data.journalPage+1)})}>Next</button></div><details><summary>Account balances · Debit less credit</summary>{Object.entries(data.balances).map(([k,v])=><p key={k}>{k}: {money(v)}</p>)}</details></section></>}
 {view==='checks'&&<section className={css.panel}><h2>Verification results</h2><p>{data.checks.filter(c=>c.passed).length} of {data.checks.length} checks passed. These check defined calculations and bookkeeping; they do not validate population representativeness or clinical appropriateness.</p>{data.checks.map(c=><div className={css.check} key={c.name}><strong>{c.passed?'Passed':'Failed'}</strong><div><h3>{c.name}</h3><p>{c.detail}</p></div></div>)}</section>}
 {view==='sources'&&<section className={css.panel}><h2>Real references. Explicit assumptions.</h2><h3>Public data</h3><p>Drug names, 11-digit NDCs, pricing units, NADAC unit prices, publication dates and effective dates come from the CMS file. Each paid claim retains its source row number. Prices are selected as of the service date, never from a later snapshot.</p><a href={data.meta.source}>Download source file ↗</a><p className={css.note}>Retrieved {data.meta.retrievedAt} · SHA-256 {data.meta.sourceHash}</p><h3>Synthetic rules</h3><p>{data.meta.terms}</p><h3>Limits</h3><p>Members, prescribing patterns, days supply, quantities, plan tiers, PA decisions, pharmacy networks, rates and financial events are generated assumptions. This is not a Caremark contract, licensed drug classification file or clinically validated population. Specialty is a synthetic plan tier. No family accumulators, drug interactions, diagnosis-based criteria, tax accounting or bank integration are modeled.</p><p>The guided correction flow uses the older small book; it is preserved under Guided correction. This larger book supports inspection and financial reconciliation, not automated benefit activation.</p></section>}
 </>}
 </div>;
}
