import {randomUUID,createHash} from 'node:crypto';
import {prisma} from '@/lib/db';
import {tenantSponsorId} from '@/lib/config';
import {createState,execute,type State,type Action} from './core';
import {verify} from './verifier';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const scope=(sponsor:string)=>({tenantId:tenantSponsorId(),sponsorId:sponsor});
export async function create(sponsor:string,key:string){const state=createState(),unique=hash(['connected-demo-1',tenantSponsorId(),sponsor,key]);let row;try{row=await prisma.assuranceRun.upsert({where:{key:unique},update:{},create:{id:'cdm_'+randomUUID(),key:unique,...scope(sponsor),cutoff:new Date(),state:JSON.stringify(state),inputHash:hash(state.original),sealedAnswer:'{}',commitment:hash(state)}});}catch(e){if((e as {code?:string}).code!=='P2002')throw e;row=await prisma.assuranceRun.findUnique({where:{key:unique}});if(!row)throw e;}return row.id;}
export async function read(sponsor:string,cutoff:Date,id?:string){if(id&&!id.startsWith('cdm_'))return null;const row=await prisma.assuranceRun.findFirst({where:{...scope(sponsor),id:id??{startsWith:'cdm_'},createdAt:{lte:cutoff}},orderBy:{createdAt:'desc'}});if(!row)return null;const state=JSON.parse(row.state) as State;if(hash(state)!==row.commitment)throw Error('Evidence integrity check failed');if(state.events.some(e=>new Date(e.at)>cutoff))throw Error('Later activity unavailable at this cutoff');return {id:row.id,revision:row.revision,state};}
export async function command(sponsor:string,c:{id:string;revision:number;key:string;action:Action},actor:string){await prisma.$transaction(async tx=>{const row=await tx.assuranceRun.findFirst({where:{id:c.id,...scope(sponsor)}});if(!row||!row.id.startsWith('cdm_'))throw Error('Run unavailable');const state=JSON.parse(row.state) as State;if(hash(state)!==row.commitment||hash(state.original)!==row.inputHash)throw Error('Evidence integrity check failed');if(state.commands[c.key]){if(state.commands[c.key]!==hash(c))throw Error('Conflicting retry');return;}if(row.revision!==c.revision)throw Error('Stale revision; refresh');if(c.action==='verify'){if(!['Settled','Verified'].includes(state.stage))throw Error('Complete the preceding step first');state.checks=verify(state);state.stage=state.checks.every(c=>c.passed)?'Verified':'Settled';state.events.push({at:new Date().toISOString(),role:'Independent verifier · Deterministic',action:`${state.checks.filter(c=>c.passed).length} of ${state.checks.length} checks passed.`});}else execute(state,c.action,actor);state.commands[c.key]=hash(c);const updated=await tx.assuranceRun.updateMany({where:{id:row.id,...scope(sponsor),revision:row.revision},data:{state:JSON.stringify(state),commitment:hash(state),revision:row.revision+1}});if(!updated.count)throw Error('Stale revision; refresh');},{timeout:15000});}
