import prices from '../../../data/realistic-book/prices.json';
export type Member={id:string;household:string;age:number;relationship:string;plan:'Copay'|'HDHP';start:string;end:string|null};
export type Claim={id:string;memberId:string;date:string;ndc:string;drug:string;tier:string;quantity:number;days:number;unit:string;channel:string;pharmacy:string;prescriber:string;status:'Paid'|'Rejected'|'Reversal'|'Not verified';reason:string;originalId?:string;allowed:number;member:number;employer:number;deductibleBefore:number;deductibleAfter:number;oopBefore:number;oopAfter:number;price?:{rate:string;asOf:string;effective:string;line:number};pa:string;settlementDate?:string;rebate:number};
export type Journal={id:string;date:string;claimId?:string;batch?:string;description:string;lines:{account:string;debit:number;credit:number}[]};
export type Rebate={id:string;period:string;claimIds:string[];entitlement:number;manufacturerReceived:number;topup:number;due:string;status:string};
export type Book={version:2;seed:number;createdAt:string;cutoff:string;members:Member[];claims:Claim[];journal:Journal[];rebates:Rebate[];checks:{name:string;passed:boolean;detail:string}[]};
export const META={members:240,start:'2026-01-08',end:'2026-09-30',source:prices.source,sourceHash:prices.sha256,retrievedAt:prices.retrievedAt,terms:'Synthetic commercial terms: reimbursement = dated NADAC × quantity + $2 retail / $4 mail / $8 specialty. Copay plan: generic $10, brand $45, specialty 20% capped at $150 per fill; mail copays ×2. HDHP: $500 individual deductible, then 20%; metformin bypasses the deductible. Both plans: $2,500 individual OOP maximum. $2 administration fee per net paid claim. Manufacturer rebate assumptions: brand $30, specialty $300 per net fill; brand client guarantee $40 inclusive of manufacturer rebate. Quarterly reconciliation due 75 days after quarter end. All manufacturer entitlements credited in full at reconciliation, even when collections are partial. No family accumulator or clinical appropriateness modeling.'};
const iso=(s:string)=>{const [m,d,y]=s.split('/');return `${y}-${m}-${d}`;};
const addDays=(date:string,n:number)=>new Date(Date.parse(date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
const month=(date:string)=>date.slice(0,7);
export function reference(ndc:string,date:string){return prices.rows.filter(r=>r.NDC===ndc&&iso(r['As of Date'])<=date&&iso(r['Effective Date'])<=date).sort((a,b)=>iso(b['As of Date']).localeCompare(iso(a['As of Date']))||iso(b['Effective Date']).localeCompare(iso(a['Effective Date'])))[0];}
export function ingredientCents(rate:string,quantity:number){const [whole,fraction='']=rate.split('.'),[qWhole,qFraction='']=String(quantity).split('.');const numerator=BigInt(whole+fraction)*BigInt(qWhole+qFraction)*BigInt(100),denominator=BigInt(10)**BigInt(fraction.length+qFraction.length);return Number((numerator+denominator/BigInt(2))/denominator);}
export function costShare(allowed:number,plan:Member['plan'],tier:string,mail:boolean,deductible:number,oop:number,exempt:boolean){const remaining=Math.max(0,250000-oop),dedApplied=plan==='HDHP'&&!exempt?Math.min(allowed,Math.max(0,50000-deductible),remaining):0;const scheduled=plan==='HDHP'?dedApplied+Math.round((allowed-dedApplied)*.2):tier==='Specialty'?Math.min(15000,Math.round(allowed*.2)):(tier==='Brand'?4500:1000)*(mail?2:1);const member=Math.min(allowed,remaining,scheduled);return {member,employer:allowed-member,deductibleAfter:deductible+dedApplied,oopAfter:oop+member};}
export function generate(seed=7319):Book{
 const book:Book={version:2,seed,createdAt:new Date().toISOString(),cutoff:META.end,members:[],claims:[],journal:[],rebates:[],checks:[]};
 let serial=0;const accum=new Map<string,{ded:number;oop:number}>();
 const post=(id:string,date:string,description:string,amount:number,debit:string,credit:string,claimId?:string,batch?:string)=>{if(amount)book.journal.push({id,date,description,claimId,batch,lines:[{account:debit,debit:amount,credit:0},{account:credit,debit:0,credit:amount}]});};
 const random=(i:number,salt:number)=>((Math.imul(i+seed,1103515245)+Math.imul(salt,12345))>>>0)/4294967296;
 type Scheduled={member:Member;drug:number;date:string;mail:boolean;quantityLimit:boolean;out:boolean;reverse:boolean};const schedule:Scheduled[]=[];
 for(let i=0;i<240;i++){
  const child=i>=180,member:Member={id:`SYN-M${String(i+1).padStart(4,'0')}`,household:`SYN-H${String(i<120?i+1:(i-120)%120+1).padStart(3,'0')}`,age:child?Math.max(2,Math.min(2+i%16,22+((i%120)*7)%43-20)):22+(i*7)%43,relationship:i<120?'Employee':child?'Child':'Spouse',plan:(i%120)%2?'HDHP':'Copay',start:(i%120)%19===0?'2026-04-01':'2026-01-01',end:(i%120)%23===0?'2026-06-15':null};book.members.push(member);accum.set(member.id,{ded:0,oop:0});
  if(i%6===0)continue; // Explicit non-users.
  const chronic=child?[]:i<5?[11+(i%4>=2?1:0)]:[i%8,...(i%3===0?[(i+3)%8]:[]),...(i%11===0?[9+i%2]:[])];
  for(let mo=1;mo<=9;mo++)for(const d of chronic){if(mo===5&&i%13===0)continue;const mail=d<8&&i%5===0;if(mail&&(mo-1)%3)continue;schedule.push({member,drug:d,date:`2026-${String(mo).padStart(2,'0')}-${String(8+i%19).padStart(2,'0')}`,mail,quantityLimit:mo===3&&i%17===0,out:mo===2&&i%29===0,reverse:mo===5&&i%31===0});}
  for(const mo of [2+(i%3),7+(i%2)])if((!child||member.age>=6)&&random(i,mo)>.3)schedule.push({member,drug:child?13:(i%2?8:13),date:`2026-0${mo}-${String(9+i%18).padStart(2,'0')}`,mail:false,quantityLimit:false,out:false,reverse:i%37===0});
 }
 schedule.sort((a,b)=>a.date.localeCompare(b.date)||a.member.id.localeCompare(b.member.id)||a.drug-b.drug);
 function adjudicate(e:Scheduled,date:string,retry=false,originalId?:string):Claim{
  const d=prices.drugs[e.drug],a=accum.get(e.member.id)!,channel=d.tier==='Specialty'?'Specialty':e.mail?'Mail':'Retail',ref=reference(d.ndc,date),quantity=d.quantity*(e.mail?3:1)*(e.quantityLimit&&!retry?2:1),days=e.mail?90:d.days;
  let reason='';if(date<e.member.start||e.member.end&&date>e.member.end)reason='Eligibility inactive';else if(e.out&&!retry)reason='Out-of-network pharmacy';else if(e.quantityLimit&&!retry)reason='Quantity limit exceeded';else if(d.pa&&!retry&&(date<'2026-02-01'||date>='2026-07-01'&&date<'2026-08-01'))reason='Prior authorization required';
  const allowed=reason||!ref?0:ingredientCents(ref['NADAC Per Unit'],quantity)+(channel==='Specialty'?800:e.mail?400:200);
  const share=costShare(allowed,e.member.plan,d.tier,e.mail,a.ded,a.oop,e.drug===0);
  const c:Claim={id:`RB-C${String(++serial).padStart(6,'0')}`,memberId:e.member.id,date,ndc:d.ndc,drug:d.name,tier:d.tier,quantity,days,unit:ref?.['Pricing Unit']??'Unavailable',channel,pharmacy:e.out&&!retry?'SYN-OUT-01':channel==='Specialty'?'SYN-SP-01':e.mail?'SYN-MAIL-01':`SYN-RX-${1+Number(e.member.id.slice(-2))%5}`,prescriber:`SYN-PR-${1+Number(e.member.id.slice(-2))%12}`,status:reason?'Rejected':ref?'Paid':'Not verified',reason:reason||(!ref?'No dated public reference available':''),originalId,allowed,member:share.member,employer:share.employer,deductibleBefore:a.ded,deductibleAfter:share.deductibleAfter,oopBefore:a.oop,oopAfter:share.oopAfter,pa:d.pa?(reason==='Prior authorization required'?'Missing':retry?'Synthetic approval on resubmission':'Synthetic authorization in force'):'Not required by synthetic formulary',...(ref?{price:{rate:ref['NADAC Per Unit'],asOf:iso(ref['As of Date']),effective:iso(ref['Effective Date']),line:ref.line}}:{}),rebate:reason||!ref?0:d.tier==='Brand'?3000:d.tier==='Specialty'?30000:0};
  if(c.status==='Paid'){a.ded=c.deductibleAfter;a.oop=c.oopAfter;post(c.id+'-claim',date,'Plan liability for paid claim',c.employer,'Employer receivable','Pharmacy payable',c.id);post(c.id+'-fee',date,'Disclosed administration fee',200,'Employer receivable','Fee revenue',c.id);const settlement=addDays(date,14);if(settlement<=book.cutoff&&!e.reverse){c.settlementDate=settlement;post(c.id+'-settle',settlement,'Synthetic pharmacy remittance',c.employer,'Pharmacy payable','Cash',c.id);}}
  book.claims.push(c);return c;
 }
 // Resubmissions are scheduled in true date order so they cannot see later accumulators.
 type Event={item:Scheduled;date:string;retry?:boolean;original?:string};const events:Event[]=schedule.map(item=>({item,date:item.date}));
 while(events.length){events.sort((a,b)=>a.date.localeCompare(b.date)||a.item.member.id.localeCompare(b.item.member.id)||a.item.drug-b.item.drug);const e=events.shift()!;if(e.date>book.cutoff)continue;const c=adjudicate(e.item,e.date,e.retry,e.original);
  if(c.status==='Rejected'&&c.reason!=='Eligibility inactive'&&!e.retry)events.push({item:{...e.item,reverse:false},date:addDays(e.date,3),retry:true,original:c.id});
  if(c.status==='Paid'&&e.item.reverse){const a=accum.get(c.memberId)!;a.ded=c.deductibleBefore;a.oop=c.oopBefore;const reversal:Claim={...c,id:`RB-C${String(++serial).padStart(6,'0')}`,status:'Reversal',reason:'Synthetic same-day cancellation',originalId:c.id,allowed:-c.allowed,member:-c.member,employer:-c.employer,rebate:-c.rebate,deductibleBefore:c.deductibleAfter,deductibleAfter:c.deductibleBefore,oopBefore:c.oopAfter,oopAfter:c.oopBefore};book.claims.push(reversal);post(reversal.id+'-claim',c.date,'Reverse unpaid claim liability',c.employer,'Pharmacy payable','Employer receivable',reversal.id);post(reversal.id+'-fee',c.date,'Reverse administration fee',200,'Fee revenue','Employer receivable',reversal.id);}
 }
 const reversed=new Set(book.claims.filter(c=>c.status==='Reversal').map(c=>c.originalId));
 for(let q=1;q<=3;q++){const paid=book.claims.filter(c=>c.status==='Paid'&&!reversed.has(c.id)&&Math.ceil(Number(c.date.slice(5,7))/3)===q&&c.rebate>0),entitlement=paid.reduce((n,c)=>n+c.rebate,0),topup=paid.filter(c=>c.tier==='Brand').length*1000,period=`2026-Q${q}`,close=['2026-03-31','2026-06-30','2026-09-30'][q-1],due=addDays(close,75),received=due<=book.cutoff?Math.round(entitlement*(q===2?.9:1)):0;
  book.rebates.push({id:period,period,claimIds:paid.map(c=>c.id),entitlement,manufacturerReceived:received,topup,due,status:due>book.cutoff?'Accrued · Not due':received<entitlement?'Partial collection · Difference open':'Collected'});
  post(period+'-accrual',close,'Manufacturer entitlement, not a cash receipt',entitlement,'Manufacturer receivable','Employer rebate payable',undefined,period);
  if(due<=book.cutoff){post(period+'-receipt',due,'Synthetic manufacturer receipt',received,'Cash','Manufacturer receivable',undefined,period);post(period+'-credit',due,'100% employer entitlement credited despite collection shortfall',entitlement,'Employer rebate payable','Employer receivable',undefined,period);post(period+'-guarantee',due,'PBM-funded guarantee top-up; legitimate expense',topup,'Guarantee expense','Employer receivable',undefined,period);}
 }
 // Monthly client invoices use net claim/fee postings and quarterly credits on their actual dates.
 for(let m=1;m<=9;m++){const period=`2026-${String(m).padStart(2,'0')}`,amount=book.journal.filter(j=>month(j.date)===period&&!j.id.endsWith('-client-payment')).flatMap(j=>j.lines).filter(l=>l.account==='Employer receivable').reduce((n,l)=>n+l.debit-l.credit,0),due=`2026-${String(m+1).padStart(2,'0')}-15`;if(due<=book.cutoff&&amount>0)post(period+'-client-payment',due,'Synthetic monthly employer payment',amount,'Cash','Employer receivable',undefined,period);}
 book.journal.sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));return book;
}
