import {NextResponse} from 'next/server';
import {z} from 'zod';
import {demoFeaturesEnabled} from '@/lib/config';
import {authenticatedStaff,sameOrigin} from '@/lib/contract-checks/access';
import {getClock} from '@/lib/session';
import {selectedSponsor} from '@/lib/contract-checks/context';
import {create,read,summary} from '@/lib/realistic-book/service';
import {META} from '@/lib/realistic-book/core';
export async function GET(req:Request){if(!demoFeaturesEnabled())return NextResponse.json({error:'Unavailable'},{status:404});if(!await authenticatedStaff())return NextResponse.json({error:'Access denied'},{status:403});try{const q=new URL(req.url).searchParams,run=await read(await selectedSponsor(),(await getClock()).now,q.get('id')??undefined);if(!run)return NextResponse.json({run:null,meta:META});const {book,id}=run;if(q.get('export')==='1')return NextResponse.json({id,meta:META,book},{headers:{'Content-Disposition':'attachment; filename="glass-realistic-synthetic-book.json"','Cache-Control':'no-store'}});const search=(q.get('q')??'').toLowerCase().slice(0,100),status=q.get('status'),channel=q.get('channel'),period=q.get('month');const filtered=book.claims.filter(c=>(!status||c.status===status)&&(!channel||c.channel===channel)&&(!period||c.date.startsWith(period))&&(!search||[c.id,c.memberId,c.drug,c.ndc,c.pharmacy].join(' ').toLowerCase().includes(search)));const page=Math.min(Math.max(1,Math.floor(Number(q.get('page')))||1),Math.max(1,Math.ceil(filtered.length/25)));const claim=book.claims.find(c=>c.id===q.get('claim'));const journalRows=book.journal.filter(j=>(!period||j.date.startsWith(period))&&(!search||JSON.stringify(j).toLowerCase().includes(search)));const journalPages=Math.max(1,Math.ceil(journalRows.length/50)),journalPage=Math.min(journalPages,Math.max(1,Math.floor(Number(q.get('jp')))||1));const invoices=Array.from({length:9},(_,i)=>{const period='2026-'+String(i+1).padStart(2,'0');const postings=book.journal.filter(j=>j.date.startsWith(period)&&!j.id.endsWith('-client-payment'));return {period,amount:postings.flatMap(j=>j.lines).filter(l=>l.account==='Employer receivable').reduce((n,l)=>n+l.debit-l.credit,0),paid:book.journal.find(j=>j.id===period+'-client-payment')?.lines.find(l=>l.account==='Cash')?.debit??0};});const balances:Record<string,number>={};for(const j of book.journal)for(const l of j.lines)balances[l.account]=(balances[l.account]??0)+l.debit-l.credit;return NextResponse.json({run:{id,createdAt:book.createdAt,cutoff:book.cutoff},meta:META,summary:summary(book),claims:filtered.slice((page-1)*25,page*25),total:filtered.length,page,pages:Math.max(1,Math.ceil(filtered.length/25)),members:book.members.map(m=>({...m,claims:book.claims.filter(c=>c.memberId===m.id).length})),rebates:book.rebates,checks:book.checks,balances,invoices,journal:journalRows.slice((journalPage-1)*50,journalPage*50),journalCount:journalRows.length,journalPage,journalPages,selected:claim?{claim,member:book.members.find(m=>m.id===claim.memberId),history:book.claims.filter(c=>c.memberId===claim.memberId),journal:book.journal.filter(j=>j.claimId===claim.id),rebate:book.rebates.find(r=>r.claimIds.includes(claim.id))}:null},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'Unable to load book'},{status:409});}}
export async function POST(req:Request){if(!demoFeaturesEnabled())return NextResponse.json({error:'Unavailable'},{status:404});if(!sameOrigin(req)||!await authenticatedStaff())return NextResponse.json({error:'Access denied'},{status:403});const c=z.object({key:z.uuid()}).strict().safeParse(await req.json().catch(()=>null));if(!c.success)return NextResponse.json({error:'Invalid request'},{status:400});if((await getClock()).pinned)return NextResponse.json({error:'Return to the current clock to generate a book'},{status:409});try{return NextResponse.json({id:await create(await selectedSponsor(),c.data.key)});}catch{return NextResponse.json({error:'Unable to generate book'},{status:409});}}
