import {NextResponse} from 'next/server';
import {z} from 'zod';
import {demoFeaturesEnabled} from '@/lib/config';
import {authenticatedStaff,sameOrigin} from '@/lib/contract-checks/access';
import {selectedSponsor} from '@/lib/contract-checks/context';
import {getClock,getSessionUser} from '@/lib/session';
import {create,read,command} from '@/lib/connected-demo/service';
import {TERMS,forecast,memberAnswer,createState} from '@/lib/connected-demo/core';
const schema=z.discriminatedUnion('action',[z.object({action:z.literal('create'),key:z.uuid()}).strict(),z.object({action:z.enum(['scan','approve','reject','repair','settle','verify']),id:z.string().startsWith('cdm_').max(60),revision:z.number().int().nonnegative(),key:z.uuid()}).strict()]);
function failure(e:unknown){const m=e instanceof Error?e.message:'';return NextResponse.json({error:['Run unavailable','Stale revision; refresh','Conflicting retry','Complete the preceding step first','Evidence integrity check failed','Later activity unavailable at this cutoff','Return to the current clock'].includes(m)?m:'Unable to complete request'},{status:409});}
export async function GET(req:Request){if(!demoFeaturesEnabled())return NextResponse.json({error:'Unavailable'},{status:404});if(!await authenticatedStaff())return NextResponse.json({error:'Access denied'},{status:403});try{const q=new URL(req.url).searchParams,run=await read(await selectedSponsor(),(await getClock()).now,q.get('id')??undefined),s=run?.state??createState();const index=0;return NextResponse.json({run,terms:TERMS,forecast:forecast(s),answers:run?{cost:memberAnswer(s,'cost',index),refund:memberAnswer(s,'refund',index),access:memberAnswer(s,'access',index)}:{cost:'Start a demonstration to inspect the recorded claim.',refund:'No demonstration run selected. No refund has been recorded.',access:'Start a demonstration to inspect its modeled access changes.'}},{headers:{'Cache-Control':'no-store',...(q.get('export')==='1'?{'Content-Disposition':'attachment; filename="glass-connected-proof.json"'}:{})}});}catch(e){return failure(e);}}
export async function POST(req:Request){if(!demoFeaturesEnabled())return NextResponse.json({error:'Unavailable'},{status:404});if(!sameOrigin(req)||!await authenticatedStaff())return NextResponse.json({error:'Access denied'},{status:403});const c=schema.safeParse(await req.json().catch(()=>null));if(!c.success)return NextResponse.json({error:'Invalid command'},{status:400});try{if((await getClock()).pinned)throw Error('Return to the current clock');const sponsor=await selectedSponsor();if(c.data.action==='create')return NextResponse.json({id:await create(sponsor,c.data.key)});await command(sponsor,c.data,(await getSessionUser())?.email??'Identity not recorded');return NextResponse.json({id:c.data.id});}catch(e){return failure(e);}}
